-- Vietnamese translations for 7 KB articles that were missing -vi counterparts.
-- Articles from: 20260529100000_knowledge_base_new_articles.sql (5 articles)
--                20260529100000 new batch (understanding-audit-trail, understanding-workflow-versions)

INSERT INTO knowledge_base (title, slug, content_markdown, category, is_active) VALUES

(
  'Cách cấu hình quy tắc phân công',
  'how-to-configure-assignee-rules-vi',
  E'# Cách cấu hình quy tắc phân công\n\nQuy tắc phân công xác định ai sẽ nhận từng bước trong quy trình. Bạn đặt chúng trong trình xây dựng quy trình trên mỗi nút Hành động hoặc Rẽ nhánh.\n\n## Các loại quy tắc\n\n**Người yêu cầu**\nBước được phân công cho người đã khởi động quy trình. Dùng cho các bước mà chính người gửi phải điền (ví dụ: cung cấp thêm thông tin).\n\n**Quản lý trực tiếp của người yêu cầu**\nBước được phân công cho quản lý trực tiếp của người yêu cầu (theo cấu hình trong danh sách Người dùng). Dùng cho các phê duyệt cấp một.\n\n**Quản lý cấp trên**\nBước được phân công cho quản lý của quản lý — một cấp trên quản lý trực tiếp của người yêu cầu. Dùng cho các phê duyệt cấp cao hơn.\n\n**Trưởng phòng ban**\nBước được phân công cho trưởng phòng ban của người yêu cầu. Trưởng phòng ban được cấu hình trong Quản lý phòng ban.\n\n**Người cố định (email)**\nBước luôn được phân công cho một người cụ thể, được xác định bằng địa chỉ email. Dùng cho các bước luôn phải đến một người nhất định (ví dụ: Giám đốc tài chính cho tất cả phê duyệt tài chính). Nếu người đó bị vô hiệu hóa, quy trình sẽ báo lỗi — hãy cập nhật quy tắc kịp thời.\n\n**Vai trò trong phòng ban**\nBước được phân công cho người dùng có vai trò cụ thể (Quản trị viên hoặc Thành viên) trong một phòng ban nhất định.\n\n## Cách đặt quy tắc phân công\n\n1. Nhấn vào nút Hành động hoặc Rẽ nhánh trên canvas\n2. Trong bảng cấu hình bên phải, cuộn đến phần Người được phân công\n3. Chọn loại quy tắc từ menu thả xuống\n4. Điền các trường bổ sung (ví dụ: chọn phòng ban cho "Trưởng phòng ban" hoặc "Vai trò trong phòng ban")\n\n## Nếu không tìm thấy người phù hợp?\n\nNếu quy tắc không thể xác định được người dùng (ví dụ: phòng ban chưa có trưởng phòng, hoặc người được chỉ định theo email đã bị vô hiệu hóa), bước quy trình sẽ báo lỗi kèm mô tả chi tiết. Vào Quản trị → Phiên để xem nhật ký lỗi, sau đó sửa vấn đề và khởi động lại phiên mới.',
  'how-to',
  true
),

(
  'Cách cấu hình điều kiện rẽ nhánh',
  'how-to-configure-branch-conditions-vi',
  E'# Cách cấu hình điều kiện rẽ nhánh\n\nNút rẽ nhánh chia quy trình thành đường Có và đường Không dựa trên giá trị từ một bước trước đó. Điều này cho phép bạn xây dựng quy trình phê duyệt với các kết quả khác nhau (ví dụ: được duyệt hoặc bị từ chối).\n\n## Thêm nút rẽ nhánh\n\n1. Trên canvas, nhấn nút + trên một nút hiện có và chọn Rẽ nhánh\n2. Kết nối tay cầm Có và Không với các bước tiếp theo khác nhau\n3. Nhấn vào nút rẽ nhánh để mở bảng cấu hình\n\n## Đặt điều kiện\n\nMỗi đường (Có / Không) có thể có một hoặc nhiều điều kiện. Tất cả điều kiện trong một nhóm phải đúng để đường đó được chọn.\n\n1. Trong bảng cấu hình, nhấn Thêm điều kiện dưới nhóm Có hoặc Không\n2. Chọn bước và trường phía trước để đọc giá trị\n3. Chọn toán tử\n4. Nhập giá trị để so sánh\n\n## Các toán tử có sẵn\n\n| Toán tử | Ý nghĩa | Loại trường |\n|---------|---------|-------------|\n| bằng | Khớp chính xác (không phân biệt hoa thường) | Tất cả |\n| không bằng | Không khớp | Tất cả |\n| chứa | Giá trị trường bao gồm văn bản | Văn bản, Văn bản dài, Hộp kiểm |\n| lớn hơn | So sánh số | Số |\n| nhỏ hơn | So sánh số | Số |\n| lớn hơn hoặc bằng | So sánh số | Số |\n| nhỏ hơn hoặc bằng | So sánh số | Số |\n\n## Dùng AI để phân tích điều kiện\n\nThay vì điền điều kiện thủ công, hãy nhập quy tắc bằng ngôn ngữ tự nhiên vào ô AI ở cuối mỗi nhóm điều kiện và nhấn Enter. Ví dụ:\n\n- "số tiền lớn hơn 1000"\n- "quyết định bằng Đồng ý"\n- "loại nghỉ phép chứa năm phép"\n\nBizFlow sẽ tự động ánh xạ mô tả của bạn sang trường, toán tử và giá trị phù hợp.\n\n## Chỉnh sửa toán tử thủ công\n\nBạn cũng có thể thay đổi toán tử trực tiếp trên bất kỳ hàng điều kiện nào bằng cách nhấn vào menu thả xuống toán tử giữa bộ chọn trường và ô nhập giá trị.',
  'how-to',
  true
),

(
  'Cách thiết lập thông báo qua Slack và Teams',
  'how-to-setup-webhook-notifications-vi',
  E'# Cách thiết lập thông báo qua Slack và Teams\n\nBizFlow có thể gửi thông báo phân công bước và cảnh báo SLA quá hạn trực tiếp đến kênh Slack hoặc Microsoft Teams, bên cạnh email.\n\n## Thiết lập Slack\n\n1. Trong Slack, truy cập **api.slack.com/apps** và tạo ứng dụng mới (hoặc dùng ứng dụng hiện có)\n2. Bật **Incoming Webhooks** và thêm vào kênh bạn muốn nhận thông báo\n3. Sao chép URL webhook (bắt đầu bằng `https://hooks.slack.com/services/...`)\n4. Trong BizFlow, vào **Cài đặt → Tích hợp** (chỉ quản trị viên)\n5. Dán URL vào trường **URL Webhook Slack**\n6. Nhấn **Kiểm tra** để gửi thông báo thử và xác nhận đã nhận\n7. Nhấn **Lưu**\n\n## Thiết lập Microsoft Teams\n\n1. Trong Teams, mở kênh bạn muốn và nhấn **Quản lý kênh → Trình kết nối**\n2. Thêm trình kết nối **Incoming Webhook** và đặt tên\n3. Sao chép URL webhook (bắt đầu bằng `https://...webhook.office.com/webhookb2/...`)\n4. Trong BizFlow, vào **Cài đặt → Tích hợp**\n5. Dán URL vào trường **URL Webhook Teams**\n6. Nhấn **Kiểm tra** để xác nhận, rồi nhấn **Lưu**\n\n## Các thông báo được gửi\n\n- **Bước được phân công**: mỗi khi một bước quy trình được phân công cho ai đó trong nhóm, tin nhắn sẽ được đăng lên kênh đã cấu hình\n- **SLA quá hạn**: một lần mỗi ngày, nếu có các bước quá hạn hoặc sắp đến hạn trong nhóm, một bản tóm tắt sẽ được đăng\n\n## Lưu ý\n\n- Bạn có thể cấu hình cả Slack và Teams cùng lúc — thông báo sẽ được gửi đến cả hai\n- URL webhook là theo tổ chức, không phải theo người dùng\n- Để dừng thông báo, xóa trường URL và lưu',
  'how-to',
  true
),

(
  'Cách đăng nhập bằng Google',
  'how-to-sign-in-with-google-vi',
  E'# Cách đăng nhập bằng Google\n\nBizFlow hỗ trợ đăng nhập bằng tài khoản Google thay thế cho email và mật khẩu.\n\n## Đăng nhập bằng Google\n\n1. Truy cập trang đăng nhập BizFlow\n2. Nhấn **Tiếp tục với Google**\n3. Chọn tài khoản Google và cấp quyền\n4. Bạn sẽ được chuyển đến không gian làm việc BizFlow\n\n## Lần đầu dùng đăng nhập Google\n\nNếu địa chỉ email của bạn khớp với tài khoản BizFlow hiện có (ví dụ: được tạo bởi lời mời từ quản trị viên), đăng nhập Google sẽ tự động liên kết và bạn sẽ được đăng nhập vào tài khoản đó.\n\nNếu chưa có tài khoản cho email Google của bạn, bạn cần đăng ký trước hoặc yêu cầu quản trị viên mời bạn.\n\n## Xác thực hai yếu tố (MFA) khi đăng nhập Google\n\nNếu bạn đã thiết lập xác thực TOTP hai yếu tố cho tài khoản BizFlow khi đăng nhập bằng email/mật khẩu, lưu ý rằng đăng nhập Google hiện tại bỏ qua bước MFA. Đây là hạn chế đã biết — lời nhắc nhập mã chỉ xuất hiện khi đăng nhập bằng email và mật khẩu. Nếu tổ chức yêu cầu bắt buộc MFA, hãy dùng email và mật khẩu để đăng nhập.\n\n## Gặp sự cố khi đăng nhập bằng Google?\n\n- Đảm bảo bạn chọn đúng tài khoản Google khớp với email BizFlow của bạn\n- Nếu bạn bị chuyển về trang chủ thay vì không gian làm việc, hãy thử lại — điều này có thể xảy ra nếu trình duyệt chặn chuyển hướng\n- Nếu vấn đề vẫn tiếp diễn, hãy thử đăng nhập bằng email và mật khẩu, hoặc liên hệ hỗ trợ tại contact@bizflow.id.vn',
  'account',
  true
),

(
  'Cách sử dụng bình luận trong quy trình',
  'how-to-use-flow-comments-vi',
  E'# Cách sử dụng bình luận trong quy trình\n\nMỗi phiên quy trình đang chạy đều có một luồng bình luận nơi người tham gia có thể đặt câu hỏi, ghi chú hoặc báo cáo vấn đề — mà không cần quay lại email.\n\n## Ai có thể bình luận\n\n- Người đã khởi động quy trình\n- Bất kỳ ai đã được phân công một bước trong phiên (hiện tại hoặc trước đó)\n- Quản trị viên tổ chức\n\nNhững người được phân công trong tương lai (người chưa đến bước của họ) không thể xem hoặc đăng bình luận cho đến khi bước của họ được phân công.\n\n## Mở một phiên quy trình\n\nBạn có thể truy cập phiên quy trình từ nhiều nơi:\n\n- **Nhiệm vụ → Tab Đang chờ**: nhấn vào thẻ nhiệm vụ để mở bảng chi tiết\n- **Nhiệm vụ → Tab Quy trình của tôi**: nhấn vào một hàng để mở phiên bạn đã khởi động\n- **Nhiệm vụ → Tab Lịch sử**: nhấn vào một hàng bước đã hoàn thành để xem toàn bộ phiên\n- **Chuông thông báo**: nhấn vào thông báo bình luận để mở phiên trực tiếp\n- **Quản trị → Phiên**: quản trị viên có thể mở bất kỳ phiên nào từ giao diện quản trị\n\n## Đăng bình luận\n\n1. Mở một phiên quy trình\n2. Cuộn đến phần **Bình luận** bên dưới dòng thời gian bước\n3. Nhập bình luận (tối đa 2000 ký tự) và nhấn **Gửi**, hoặc nhấn Ctrl+Enter\n\nBình luận của bạn xuất hiện ngay lập tức. Tất cả người tham gia khác nhận được thông báo trong ứng dụng và, nếu tổ chức bạn đã cấu hình webhook Slack hoặc Teams, một tin nhắn kênh.\n\n## Lịch sử bình luận\n\nTheo mặc định, tất cả người tham gia có thể xem toàn bộ lịch sử bình luận từ khi quy trình bắt đầu. Quản trị viên có thể giới hạn điều này theo từng quy trình để người được phân công chỉ thấy các bình luận được đăng kể từ khi bước của họ được phân công:\n\n1. Mở quy trình trong chế độ chỉnh sửa\n2. Trong bảng Xuất bản (thanh bên phải), tìm **Lịch sử bình luận**\n3. Tắt **Hiển thị toàn bộ lịch sử cho tất cả người tham gia**\n\nNgười khởi động và quản trị viên luôn thấy toàn bộ lịch sử bất kể cài đặt này.\n\n## Lưu ý\n\n- Bình luận là một phần của hồ sơ phiên và vẫn hiển thị ngay cả sau khi quy trình hoàn thành\n- Bình luận hiện tại không thể chỉnh sửa hoặc xóa sau khi đăng',
  'how-to',
  true
),

(
  'Hiểu về nhật ký kiểm tra',
  'understanding-audit-trail-vi',
  E'# Hiểu về nhật ký kiểm tra\n\nNhật ký kiểm tra là bản ghi chỉ-thêm về các hành động quản trị quan trọng trong không gian làm việc BizFlow của bạn. Nó hỗ trợ tuân thủ, trách nhiệm giải trình và khắc phục sự cố.\n\n## Truy cập nhật ký kiểm tra\n\n1. Vào **Quản trị → Nhật ký kiểm tra** trong thanh bên trái (chỉ quản trị viên)\n2. Bảng hiển thị 1000 mục gần nhất\n3. Lọc theo loại hành động, người thực hiện hoặc khoảng thời gian\n4. Tìm kiếm theo văn bản tự do trong nhật ký hành động\n\n## Những gì được ghi lại\n\n| Hành động | Khi nào được ghi |\n|-----------|------------------|\n| **role_changed** | Quản trị viên thay đổi vai trò của người dùng khác (ví dụ: Thành viên → Quản trị viên) |\n| **flow_published** | Quản trị viên xuất bản quy trình |\n| **flow_unpublished** | Quản trị viên hủy xuất bản quy trình |\n| **step_reassigned** | Quản trị viên phân công lại thủ công bước đang chờ cho người khác |\n| **step_escalated** | Một bước được leo thang lên quản lý do vi phạm SLA |\n| **user_deactivated** | Quản trị viên vô hiệu hóa tài khoản người dùng |\n| **user_reactivated** | Quản trị viên kích hoạt lại tài khoản người dùng |\n| **tasks_bulk_reassigned** | Quản trị viên phân công lại hàng loạt tất cả nhiệm vụ đang chờ từ người dùng này sang người dùng khác |\n\n## Những gì không được ghi lại\n\n- Hoàn thành nhiệm vụ thông thường (những điều này nằm trong nhật ký sự kiện quy trình, hiển thị bên trong mỗi phiên)\n- Cập nhật hồ sơ người dùng (tên, ảnh đại diện, chức danh)\n- Thay đổi thành viên phòng ban\n\n## Lưu ý\n\n- Nhật ký kiểm tra chỉ đọc — các mục không thể chỉnh sửa hoặc xóa\n- Các mục chỉ thuộc về tổ chức của bạn\n- Mỗi mục hiển thị người thực hiện (ai), hành động (gì), đối tượng (người dùng/quy trình/bước nào) và thời gian',
  'technical',
  true
),

(
  'Hiểu về phiên bản quy trình',
  'understanding-workflow-versions-vi',
  E'# Hiểu về phiên bản quy trình\n\nMỗi lần bạn xuất bản quy trình, BizFlow lưu một phiên bản mới của canvas. Điều này có nghĩa là bạn có thể tiếp tục cải thiện quy trình mà không ảnh hưởng đến các phiên đang chạy.\n\n## Cách lập phiên bản hoạt động\n\n- Mỗi lần xuất bản tạo ra một phiên bản có số thứ tự (v1, v2, v3, ...)\n- Các phiên đang chạy luôn hoàn thành bằng phiên bản mà chúng được khởi động\n- Các phiên mới được kích hoạt sau khi xuất bản sẽ dùng phiên bản xuất bản mới nhất\n- Bạn có thể chỉnh sửa bản nháp thoải mái mà không ảnh hưởng đến phiên đang hoạt động — bản nháp được lưu tự động nhưng không tạo phiên bản mới cho đến khi bạn xuất bản\n\n## Xem lịch sử phiên bản\n\n1. Mở quy trình trong chế độ chỉnh sửa\n2. Trong thanh bên phải, mở bảng **Phiên bản**\n3. Bạn sẽ thấy danh sách tất cả phiên bản với ngày xuất bản\n4. Nhấn bất kỳ phiên bản nào để xem trước canvas tại thời điểm đó (chỉ đọc)\n\n## So sánh hai phiên bản\n\n1. Trong bảng Phiên bản, nhấn **So sánh phiên bản**\n2. Chọn hai số phiên bản (mặc định là mới nhất và trước đó)\n3. Nhấn **Xem thay đổi** — hộp thoại tóm tắt hiển thị:\n   - Các bước được thêm hoặc xóa\n   - Các bước được đổi tên, thêm/xóa trường, hoặc thay đổi quy tắc phân công\n   - Các kết nối (cạnh) được thêm hoặc xóa\n\n## Bản nháp và đã xuất bản\n\n- **Bản nháp**: bản sao làm việc hiện tại của bạn; được lưu tự động khi bạn chỉnh sửa. Không ảnh hưởng đến phiên đang hoạt động.\n- **Đã xuất bản**: phiên bản mà các lần kích hoạt quy trình mới sẽ sử dụng. Mỗi lần xuất bản tăng số phiên bản.\n\n## Lưu ý\n\n- Hủy xuất bản quy trình ngăn các phiên mới được kích hoạt nhưng không hủy các phiên đang chạy\n- Số phiên bản là nội bộ — người dùng kích hoạt quy trình luôn tự động nhận phiên bản xuất bản mới nhất',
  'technical',
  true
)

ON CONFLICT (slug) DO NOTHING;
