-- Seeds 20 common flow templates across hr, finance, it, operations, and other categories.
-- All templates are published and available to all tenant admins.
-- Assignee rules use only non-tenant-specific types (requester, manager_of_requestor,
-- skip_level, requester_dept_head) so they survive cloning without scrubbing.

INSERT INTO public.flow_templates (name, description, category, graph, is_published) VALUES

-- ── HR ────────────────────────────────────────────────────────────────────────

(
  'Leave Request',
  'Employee submits a leave request; direct manager approves or rejects; HR records the outcome.',
  'hr',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Request Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Submit Leave Request","formSchema":[{"id":"f1","type":"dropdown","label":"Leave Type","required":true,"options":["Annual Leave","Sick Leave","Emergency Leave","Unpaid Leave","Maternity / Paternity Leave"]},{"id":"f2","type":"date","label":"Start Date","required":true},{"id":"f3","type":"date","label":"End Date","required":true},{"id":"f4","type":"textarea","label":"Reason","required":false}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"Manager Approval","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"HR Processing","formSchema":[{"id":"f1","type":"text","label":"Confirmation Number","required":true},{"id":"f2","type":"textarea","label":"Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Rejection Acknowledged","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the rejection","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Employee Onboarding',
  'New hire onboarding: IT sets up accounts and equipment; manager completes orientation checklist.',
  'hr',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Onboarding Initiated","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"IT Setup & Equipment","formSchema":[{"id":"f1","type":"text","label":"Employee Name","required":true},{"id":"f2","type":"text","label":"Job Title","required":true},{"id":"f3","type":"date","label":"Start Date","required":true},{"id":"f4","type":"checkbox","label":"Equipment Required","required":false,"options":["Laptop","Monitor","Keyboard & Mouse","Phone","Access Card","Headset"]},{"id":"f5","type":"textarea","label":"Software Access Needed","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Manager Orientation","formSchema":[{"id":"f1","type":"radio","label":"Orientation Completed","required":true,"options":["Yes","No - Rescheduled"]},{"id":"f2","type":"text","label":"Buddy / Mentor Assigned","required":false},{"id":"f3","type":"textarea","label":"Onboarding Notes","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[]}},{"id":"n4","type":"complete","position":{"x":300,"y":570},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Performance Review',
  'Annual review cycle: employee self-assessment, manager rating, and HR sign-off.',
  'hr',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Review Cycle Started","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Self Assessment","formSchema":[{"id":"f1","type":"textarea","label":"Key Accomplishments","required":true},{"id":"f2","type":"textarea","label":"Areas for Improvement","required":true},{"id":"f3","type":"textarea","label":"Goals for Next Period","required":true},{"id":"f4","type":"dropdown","label":"Overall Self Rating","required":true,"options":["1 - Outstanding","2 - Exceeds Expectations","3 - Meets Expectations","4 - Needs Improvement"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Manager Review","formSchema":[{"id":"f1","type":"dropdown","label":"Performance Rating","required":true,"options":["1 - Outstanding","2 - Exceeds Expectations","3 - Meets Expectations","4 - Needs Improvement"]},{"id":"f2","type":"textarea","label":"Strengths","required":true},{"id":"f3","type":"textarea","label":"Development Areas","required":true},{"id":"f4","type":"radio","label":"Recommended for Promotion","required":true,"options":["Yes","No","Defer"]},{"id":"f5","type":"textarea","label":"Manager Comments","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[]}},{"id":"n4","type":"action","position":{"x":300,"y":580},"data":{"label":"HR Sign-off","formSchema":[{"id":"f1","type":"radio","label":"Review Acknowledged","required":true,"options":["Acknowledged","Requires Follow-up"]},{"id":"f2","type":"textarea","label":"HR Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n5","type":"complete","position":{"x":300,"y":750},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"},{"id":"e4","source":"n4","target":"n5"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Remote Work Request',
  'Employee requests work-from-home days; manager approves or rejects.',
  'hr',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Request Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Submit WFH Request","formSchema":[{"id":"f1","type":"text","label":"Requested Date(s)","required":true},{"id":"f2","type":"dropdown","label":"Work Arrangement","required":true,"options":["Full Day","Half Day","Recurring - Weekly","Recurring - Bi-weekly"]},{"id":"f3","type":"textarea","label":"Tasks to be Completed","required":true},{"id":"f4","type":"textarea","label":"Reason","required":false}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"Manager Approval","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"Approval Confirmed","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the approval","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Rejection Acknowledged","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the rejection","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Training & Development Request',
  'Employee requests a training program; manager approves; finance confirms the budget.',
  'hr',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Request Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Submit Training Request","formSchema":[{"id":"f1","type":"text","label":"Training Program Name","required":true},{"id":"f2","type":"text","label":"Provider / Institution","required":true},{"id":"f3","type":"date","label":"Training Date","required":true},{"id":"f4","type":"text","label":"Duration","required":true},{"id":"f5","type":"number","label":"Estimated Cost (USD)","required":true},{"id":"f6","type":"textarea","label":"Business Justification","required":true}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"Manager Approval","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"Finance Approval","formSchema":[{"id":"f1","type":"text","label":"Budget Code","required":true},{"id":"f2","type":"number","label":"Approved Amount (USD)","required":true},{"id":"f3","type":"textarea","label":"Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Rejection Acknowledged","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the rejection","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Employee Offboarding',
  'Structured exit process: IT revokes access and collects assets; manager conducts exit interview.',
  'hr',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Offboarding Initiated","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Asset Return & Access Revocation","formSchema":[{"id":"f1","type":"text","label":"Employee Name","required":true},{"id":"f2","type":"date","label":"Last Working Date","required":true},{"id":"f3","type":"radio","label":"Laptop Returned","required":true,"options":["Yes","No","N/A"]},{"id":"f4","type":"radio","label":"Access Card Returned","required":true,"options":["Yes","No","N/A"]},{"id":"f5","type":"radio","label":"System Access Revoked","required":true,"options":["Yes","No"]},{"id":"f6","type":"textarea","label":"Other Assets / Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Exit Interview","formSchema":[{"id":"f1","type":"radio","label":"Exit Interview Completed","required":true,"options":["Yes","No - Declined","No - Rescheduled"]},{"id":"f2","type":"dropdown","label":"Primary Reason for Leaving","required":false,"options":["Better Opportunity","Compensation","Work-Life Balance","Relocation","Retirement","Personal Reasons","Other"]},{"id":"f3","type":"radio","label":"Eligible for Rehire","required":true,"options":["Yes","No"]},{"id":"f4","type":"textarea","label":"Key Feedback","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[]}},{"id":"n4","type":"complete","position":{"x":300,"y":570},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

-- ── Finance ───────────────────────────────────────────────────────────────────

(
  'Purchase Order Request',
  'Requester submits a PO; manager approves; finance assigns a PO number and payment terms.',
  'finance',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Request Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Submit PO Request","formSchema":[{"id":"f1","type":"text","label":"Vendor Name","required":true},{"id":"f2","type":"textarea","label":"Item / Service Description","required":true},{"id":"f3","type":"number","label":"Quantity","required":true},{"id":"f4","type":"number","label":"Unit Price (USD)","required":true},{"id":"f5","type":"number","label":"Total Amount (USD)","required":true},{"id":"f6","type":"date","label":"Required Delivery Date","required":false},{"id":"f7","type":"textarea","label":"Business Justification","required":true}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"Management Approval","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"Finance Processing","formSchema":[{"id":"f1","type":"text","label":"PO Number","required":true},{"id":"f2","type":"dropdown","label":"Payment Terms","required":true,"options":["Net 15","Net 30","Net 60","Due on Receipt"]},{"id":"f3","type":"textarea","label":"Processing Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Rejection Acknowledged","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the rejection","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Expense Reimbursement',
  'Employee submits an expense claim; manager approves; finance processes the payment.',
  'finance',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Claim Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Submit Expense Claim","formSchema":[{"id":"f1","type":"date","label":"Expense Date","required":true},{"id":"f2","type":"dropdown","label":"Category","required":true,"options":["Travel","Meals & Entertainment","Accommodation","Office Supplies","Equipment","Training","Other"]},{"id":"f3","type":"number","label":"Amount (USD)","required":true},{"id":"f4","type":"textarea","label":"Description","required":true},{"id":"f5","type":"radio","label":"Receipt Attached","required":true,"options":["Yes","No"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"Manager Approval","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"number","label":"Approved Amount (USD)","required":false},{"id":"f3","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"Finance Payment","formSchema":[{"id":"f1","type":"dropdown","label":"Payment Method","required":true,"options":["Bank Transfer","Company Card Credit","Check"]},{"id":"f2","type":"text","label":"Transaction Reference","required":true},{"id":"f3","type":"textarea","label":"Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Rejection Acknowledged","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the rejection","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Invoice Approval',
  'Finance team submits a vendor invoice for approval; manager reviews; payment is processed.',
  'finance',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Invoice Received","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Invoice Submission","formSchema":[{"id":"f1","type":"text","label":"Invoice Number","required":true},{"id":"f2","type":"text","label":"Vendor Name","required":true},{"id":"f3","type":"number","label":"Invoice Amount (USD)","required":true},{"id":"f4","type":"date","label":"Invoice Date","required":true},{"id":"f5","type":"date","label":"Payment Due Date","required":true},{"id":"f6","type":"textarea","label":"Description of Services","required":true},{"id":"f7","type":"radio","label":"PO Reference Available","required":true,"options":["Yes","No"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"Finance Review","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"textarea","label":"Review Comments","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"Payment Processing","formSchema":[{"id":"f1","type":"date","label":"Scheduled Payment Date","required":true},{"id":"f2","type":"text","label":"Payment Reference","required":true},{"id":"f3","type":"textarea","label":"Notes","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Invoice Returned","formSchema":[{"id":"f1","type":"textarea","label":"Reason for Rejection","required":true}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Budget Request',
  'Department submits a budget request; finance and department head review and allocate funds.',
  'finance',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Request Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Submit Budget Request","formSchema":[{"id":"f1","type":"text","label":"Budget Category","required":true},{"id":"f2","type":"text","label":"Budget Period","required":true},{"id":"f3","type":"number","label":"Requested Amount (USD)","required":true},{"id":"f4","type":"textarea","label":"Justification","required":true},{"id":"f5","type":"textarea","label":"Expected Outcomes","required":true}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Finance & Management Approval","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Approve with Conditions","Reject"]},{"id":"f2","type":"number","label":"Approved Amount (USD)","required":false},{"id":"f3","type":"textarea","label":"Conditions / Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n4","type":"complete","position":{"x":300,"y":570},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Contract Review & Approval',
  'New or renewed contract goes through legal review, then finance review, then management sign-off.',
  'finance',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Contract Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Contract Submission","formSchema":[{"id":"f1","type":"text","label":"Contract Title","required":true},{"id":"f2","type":"text","label":"Counter-party Name","required":true},{"id":"f3","type":"number","label":"Contract Value (USD)","required":false},{"id":"f4","type":"date","label":"Contract Start Date","required":true},{"id":"f5","type":"date","label":"Contract End Date","required":false},{"id":"f6","type":"textarea","label":"Key Terms Summary","required":true},{"id":"f7","type":"file","label":"Contract Document","required":true}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Legal Review","formSchema":[{"id":"f1","type":"radio","label":"Legal Status","required":true,"options":["Approved","Approved with Redlines","Rejected"]},{"id":"f2","type":"textarea","label":"Legal Notes","required":true}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n4","type":"action","position":{"x":300,"y":580},"data":{"label":"Management Sign-off","formSchema":[{"id":"f1","type":"radio","label":"Final Decision","required":true,"options":["Signed","Rejected"]},{"id":"f2","type":"text","label":"Signed By","required":false},{"id":"f3","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"skip_level"},"branchConditions":[]}},{"id":"n5","type":"complete","position":{"x":300,"y":750},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"},{"id":"e4","source":"n4","target":"n5"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

-- ── IT ────────────────────────────────────────────────────────────────────────

(
  'IT Equipment Request',
  'Employee requests hardware; IT manager approves; IT team fulfills and records the asset.',
  'it',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Request Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Equipment Request","formSchema":[{"id":"f1","type":"dropdown","label":"Equipment Type","required":true,"options":["Laptop","Desktop","Monitor","Keyboard & Mouse","Headset","Webcam","Docking Station","Phone","Printer","Other"]},{"id":"f2","type":"text","label":"Preferred Make / Model","required":false},{"id":"f3","type":"textarea","label":"Business Justification","required":true},{"id":"f4","type":"date","label":"Required By","required":false}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"IT Manager Approval","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"IT Fulfillment","formSchema":[{"id":"f1","type":"text","label":"Asset Tag / Serial Number","required":true},{"id":"f2","type":"date","label":"Delivery Date","required":true},{"id":"f3","type":"textarea","label":"Setup Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Rejection Acknowledged","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the rejection","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Software Access Request',
  'Employee requests access to a system or application; IT provisions the account.',
  'it',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Request Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Access Request","formSchema":[{"id":"f1","type":"text","label":"Software / System Name","required":true},{"id":"f2","type":"dropdown","label":"Access Level","required":true,"options":["Read Only","Standard User","Power User","Admin"]},{"id":"f3","type":"textarea","label":"Business Justification","required":true},{"id":"f4","type":"radio","label":"Urgency","required":true,"options":["Normal","Urgent"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"IT Provisioning","formSchema":[{"id":"f1","type":"radio","label":"Access Granted","required":true,"options":["Yes","No - Rejected","No - Pending Licence"]},{"id":"f2","type":"text","label":"Account / Licence Details","required":false},{"id":"f3","type":"textarea","label":"Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n4","type":"complete","position":{"x":300,"y":570},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'IT Incident Report',
  'Staff reports a technical incident; IT diagnoses and documents the resolution.',
  'it',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Incident Reported","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Incident Report","formSchema":[{"id":"f1","type":"dropdown","label":"Incident Type","required":true,"options":["Hardware Failure","Software Error","Network Issue","Security Concern","Data Loss","Performance Problem","Other"]},{"id":"f2","type":"dropdown","label":"Severity","required":true,"options":["Critical","High","Medium","Low"]},{"id":"f3","type":"text","label":"Affected System / Equipment","required":true},{"id":"f4","type":"textarea","label":"Incident Description","required":true},{"id":"f5","type":"text","label":"Number of Users Affected","required":false}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"IT Resolution","formSchema":[{"id":"f1","type":"dropdown","label":"Resolution Status","required":true,"options":["Resolved","Workaround Applied","Escalated to Vendor","Closed - No Action Required"]},{"id":"f2","type":"textarea","label":"Root Cause","required":true},{"id":"f3","type":"textarea","label":"Resolution Steps Taken","required":true},{"id":"f4","type":"date","label":"Resolved Date","required":true}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n4","type":"complete","position":{"x":300,"y":570},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'New Employee IT Provisioning',
  'HR triggers account and equipment setup for a new hire; IT confirms everything is ready.',
  'it',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Provisioning Requested","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Provisioning Setup","formSchema":[{"id":"f1","type":"text","label":"Employee Name","required":true},{"id":"f2","type":"text","label":"Job Title","required":true},{"id":"f3","type":"text","label":"Department","required":true},{"id":"f4","type":"date","label":"Start Date","required":true},{"id":"f5","type":"checkbox","label":"Accounts to Create","required":true,"options":["Email","VPN","Slack","GitHub","CRM","ERP","Other"]},{"id":"f6","type":"textarea","label":"Special Requirements","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Provisioning Confirmation","formSchema":[{"id":"f1","type":"radio","label":"All Accounts Created","required":true,"options":["Yes - Fully Provisioned","No - Partially Complete"]},{"id":"f2","type":"textarea","label":"Pending Items / Notes","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[]}},{"id":"n4","type":"complete","position":{"x":300,"y":570},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

-- ── Operations ────────────────────────────────────────────────────────────────

(
  'Vendor Onboarding',
  'Onboard a new supplier: procurement submits details; legal reviews compliance; finance sets up payment.',
  'operations',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Onboarding Initiated","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Vendor Information","formSchema":[{"id":"f1","type":"text","label":"Vendor Company Name","required":true},{"id":"f2","type":"text","label":"Contact Name","required":true},{"id":"f3","type":"text","label":"Contact Email","required":true},{"id":"f4","type":"dropdown","label":"Vendor Type","required":true,"options":["Supplier","Service Provider","Contractor","Consultant","Distributor"]},{"id":"f5","type":"textarea","label":"Services / Products Offered","required":true},{"id":"f6","type":"text","label":"Estimated Annual Spend (USD)","required":false}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Legal & Compliance Review","formSchema":[{"id":"f1","type":"radio","label":"NDA Required","required":true,"options":["Yes","No"]},{"id":"f2","type":"radio","label":"Background Check Completed","required":true,"options":["Yes","No","N/A"]},{"id":"f3","type":"radio","label":"Compliance Status","required":true,"options":["Approved","Rejected - Further Info Needed"]},{"id":"f4","type":"textarea","label":"Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n4","type":"action","position":{"x":300,"y":580},"data":{"label":"Finance Setup","formSchema":[{"id":"f1","type":"text","label":"Vendor ID in System","required":true},{"id":"f2","type":"dropdown","label":"Payment Terms","required":true,"options":["Net 15","Net 30","Net 60","Due on Receipt"]},{"id":"f3","type":"radio","label":"Banking Details Verified","required":true,"options":["Yes","No"]},{"id":"f4","type":"radio","label":"Vendor Created in System","required":true,"options":["Yes","No"]}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[]}},{"id":"n5","type":"complete","position":{"x":300,"y":750},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"},{"id":"e4","source":"n4","target":"n5"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Business Travel Request',
  'Employee requests travel approval; manager approves; operations books transport and accommodation.',
  'operations',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Request Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Travel Request","formSchema":[{"id":"f1","type":"text","label":"Destination","required":true},{"id":"f2","type":"date","label":"Departure Date","required":true},{"id":"f3","type":"date","label":"Return Date","required":true},{"id":"f4","type":"dropdown","label":"Travel Purpose","required":true,"options":["Client Meeting","Conference / Summit","Training","Site Visit","Internal Meeting","Other"]},{"id":"f5","type":"number","label":"Estimated Budget (USD)","required":true},{"id":"f6","type":"textarea","label":"Business Justification","required":true}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"Manager Approval","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"Travel Booking","formSchema":[{"id":"f1","type":"text","label":"Booking Reference","required":true},{"id":"f2","type":"radio","label":"Flights Booked","required":true,"options":["Yes","No - Not Required"]},{"id":"f3","type":"radio","label":"Hotel Booked","required":true,"options":["Yes","No - Not Required"]},{"id":"f4","type":"textarea","label":"Travel Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Rejection Acknowledged","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the rejection","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Asset Transfer Request',
  'Tracks the physical transfer of company assets between departments or employees.',
  'operations',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Transfer Requested","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Transfer Request","formSchema":[{"id":"f1","type":"text","label":"Asset Name / Description","required":true},{"id":"f2","type":"text","label":"Asset ID / Serial Number","required":true},{"id":"f3","type":"text","label":"Current Department / Location","required":true},{"id":"f4","type":"text","label":"Transfer To (Department / Person)","required":true},{"id":"f5","type":"date","label":"Requested Transfer Date","required":true},{"id":"f6","type":"textarea","label":"Reason for Transfer","required":true}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Transfer Confirmation","formSchema":[{"id":"f1","type":"radio","label":"Transfer Completed","required":true,"options":["Yes","No - Pending","No - Cancelled"]},{"id":"f2","type":"date","label":"Actual Transfer Date","required":false},{"id":"f3","type":"text","label":"Confirmed By","required":false},{"id":"f4","type":"textarea","label":"Notes","required":false}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n4","type":"complete","position":{"x":300,"y":570},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

-- ── Other ─────────────────────────────────────────────────────────────────────

(
  'New Project Proposal',
  'Formal project proposal with sponsor review, resource approval, and project code assignment.',
  'other',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Proposal Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Project Proposal","formSchema":[{"id":"f1","type":"text","label":"Project Name","required":true},{"id":"f2","type":"dropdown","label":"Project Type","required":true,"options":["Internal","Client-facing","Research & Development","Infrastructure","Compliance","Other"]},{"id":"f3","type":"textarea","label":"Project Description","required":true},{"id":"f4","type":"number","label":"Estimated Budget (USD)","required":true},{"id":"f5","type":"date","label":"Proposed Start Date","required":true},{"id":"f6","type":"date","label":"Proposed End Date","required":false},{"id":"f7","type":"textarea","label":"Expected Benefits","required":true},{"id":"f8","type":"textarea","label":"Key Risks","required":false}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"branch","position":{"x":300,"y":410},"data":{"label":"Sponsor Review","formSchema":[{"id":"f1","type":"radio","label":"Decision","required":true,"options":["Approve","Reject"]},{"id":"f2","type":"textarea","label":"Feedback","required":false}],"assigneeRule":{"type":"skip_level"},"branchConditions":[{"id":"bc1","fieldId":"f1","operator":"eq","value":"Approve","handleId":"yes"}]}},{"id":"n4","type":"action","position":{"x":80,"y":620},"data":{"label":"Resource Allocation","formSchema":[{"id":"f1","type":"text","label":"Project Code","required":true},{"id":"f2","type":"number","label":"Approved Budget (USD)","required":true},{"id":"f3","type":"textarea","label":"Resources Assigned","required":true},{"id":"f4","type":"date","label":"Confirmed Start Date","required":true}],"assigneeRule":{"type":"requester_dept_head"},"branchConditions":[]}},{"id":"n5","type":"action","position":{"x":520,"y":620},"data":{"label":"Rejection Acknowledged","formSchema":[{"id":"f1","type":"radio","label":"I acknowledge the rejection","required":true,"options":["Acknowledged"]}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n6","type":"complete","position":{"x":300,"y":830},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4","sourceHandle":"yes"},{"id":"e4","source":"n3","target":"n5","sourceHandle":"no"},{"id":"e5","source":"n4","target":"n6"},{"id":"e6","source":"n5","target":"n6"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
),

(
  'Document Review & Sign-off',
  'Author submits a document for peer review and management sign-off before publication.',
  'other',
  '{"nodes":[{"id":"n1","type":"trigger","position":{"x":300,"y":50},"data":{"label":"Document Submitted","formSchema":[],"assigneeRule":null,"branchConditions":[]}},{"id":"n2","type":"action","position":{"x":300,"y":220},"data":{"label":"Document Submission","formSchema":[{"id":"f1","type":"text","label":"Document Title","required":true},{"id":"f2","type":"dropdown","label":"Document Type","required":true,"options":["Policy","Procedure","Report","Proposal","Agreement","Specification","Other"]},{"id":"f3","type":"text","label":"Version","required":true},{"id":"f4","type":"textarea","label":"Summary / Purpose","required":true},{"id":"f5","type":"file","label":"Document File","required":true}],"assigneeRule":{"type":"requester"},"branchConditions":[]}},{"id":"n3","type":"action","position":{"x":300,"y":400},"data":{"label":"Peer Review","formSchema":[{"id":"f1","type":"radio","label":"Review Outcome","required":true,"options":["Approved","Approved with Minor Changes","Requires Major Revision"]},{"id":"f2","type":"textarea","label":"Reviewer Comments","required":true}],"assigneeRule":{"type":"manager_of_requestor"},"branchConditions":[]}},{"id":"n4","type":"action","position":{"x":300,"y":580},"data":{"label":"Management Sign-off","formSchema":[{"id":"f1","type":"radio","label":"Final Decision","required":true,"options":["Approved for Publication","Rejected - Return to Author"]},{"id":"f2","type":"date","label":"Sign-off Date","required":false},{"id":"f3","type":"textarea","label":"Comments","required":false}],"assigneeRule":{"type":"skip_level"},"branchConditions":[]}},{"id":"n5","type":"complete","position":{"x":300,"y":750},"data":{"label":"Complete","formSchema":[],"assigneeRule":null,"branchConditions":[]}}],"edges":[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"},{"id":"e4","source":"n4","target":"n5"}],"metadata":{"schemaVersion":1}}'::jsonb,
  true
)

ON CONFLICT DO NOTHING;
