-- KB patch: add comment_added notification type + fix comments navigation to /tasks
-- English and Vietnamese articles updated via ON CONFLICT DO UPDATE.

UPDATE knowledge_base
SET content_markdown = E'# Understanding Notifications\n\nBizFlow sends notifications to keep you informed about tasks and workflow activity.\n\n## In-app notifications\n\nThe **bell icon** in the top bar shows your unread notification count.\n\n- Click the bell to see your most recent 20 notifications\n- Click a notification to mark it as read and open the relevant flow in the detail panel\n- Click **Mark all read** to clear the badge\n- Click **View all notifications** to go to the full notifications page\n\n## Types of notifications\n\n| Type | When it appears |\n|------|-----------------|\n| 📋 **Step assigned** | A workflow step has been assigned to you |\n| ✅ **Flow completed** | A workflow you triggered has been completed |\n| 💬 **Comment added** | Someone posted a comment on a flow instance you participate in |\n| ⏰ **SLA reminder** | A step you are responsible for is due soon or overdue |\n| ⚠️ **Step escalated** | A step under your management has been escalated |\n\n## Email notifications\n\nIn addition to in-app notifications, BizFlow also sends email alerts:\n\n- **Step assigned**: you receive an email when a new task is assigned to you\n- **Flow completed**: you receive an email when a flow you triggered is finished\n- **SLA digest**: a daily email listing your overdue and due-soon tasks\n- **Escalation**: your manager receives an email if one of your assigned steps is significantly overdue\n\n## Managing notifications\n\nNotifications are automatic and cannot currently be individually turned off. If you are receiving too many emails, check with your admin about SLA configuration on the workflows.',
    updated_at = now()
WHERE slug = 'understanding-notifications';

UPDATE knowledge_base
SET content_markdown = E'# Hiểu về thông báo\n\n## Thông báo trong ứng dụng\n\n**Biểu tượng chuông** trên thanh trên cùng hiển thị số thông báo chưa đọc.\n\n- Nhấn chuông để xem 20 thông báo gần nhất\n- Nhấn thông báo để đánh dấu đã đọc và mở quy trình liên quan trong bảng chi tiết\n- Nhấn **Đánh dấu tất cả đã đọc** để xóa huy hiệu\n\n## Các loại thông báo\n\n| Loại | Khi nào xuất hiện |\n|------|------------------|\n| 📋 Bước được phân công | Một bước quy trình được phân công cho bạn |\n| ✅ Quy trình hoàn thành | Quy trình bạn khởi động đã hoàn thành |\n| 💬 Bình luận mới | Có người đăng bình luận trong quy trình bạn tham gia |\n| ⏰ Nhắc nhở SLA | Bước bạn phụ trách sắp đến hạn hoặc đã quá hạn |\n| ⚠️ Bước bị leo thang | Một bước dưới sự quản lý của bạn đã bị leo thang |\n\n## Thông báo qua email\n\n- **Bước được phân công**: email khi nhiệm vụ mới được phân công cho bạn\n- **Quy trình hoàn thành**: email khi quy trình bạn khởi động kết thúc\n- **Tóm tắt SLA hàng ngày**: email liệt kê các nhiệm vụ quá hạn và sắp đến hạn\n- **Leo thang**: quản lý của bạn nhận email nếu một bước của bạn quá hạn đáng kể',
    updated_at = now()
WHERE slug = 'understanding-notifications-vi';

UPDATE knowledge_base
SET content_markdown = E'# How to Use Flow Instance Comments\n\nEvery running workflow instance has a comment thread where participants can ask questions, leave notes, or flag issues — without going back to email.\n\n## Who can comment\n\n- The person who triggered the flow\n- Anyone who has been assigned a step in the instance (past or current)\n- Organisation admins\n\nFuture assignees (people whose step has not yet been reached) cannot see or post comments until their step is assigned.\n\n## Opening a flow instance\n\nYou can reach a flow instance from several places:\n\n- **Tasks → Pending tab**: click a pending task card to open the detail panel\n- **Tasks → My Flows tab**: click a row to open the instance you triggered\n- **Tasks → History tab**: click a completed step row to view the full instance\n- **Notification bell**: click a comment notification to open the instance directly\n- **Admin → Instances**: admins can open any instance from the admin view\n\n## Posting a comment\n\n1. Open a workflow instance\n2. Scroll to the **Comments** section below the step timeline\n3. Type your comment (up to 2000 characters) and click **Send**, or press Ctrl+Enter\n\nYour comment appears immediately. All other participants receive an in-app notification and, if your organisation has Slack or Teams webhooks configured, a channel message.\n\n## Comment history\n\nBy default, all participants can see the full comment history from when the flow started. Admins can restrict this per-flow so that assignees only see comments posted from the time their step was assigned:\n\n1. Open the flow in edit mode\n2. In the Publish panel (right sidebar), find **Comment history**\n3. Toggle off **Show full history to all participants**\n\nTriggers and admins always see the full history regardless of this setting.\n\n## Notes\n\n- Comments are part of the instance record and remain visible even after the flow completes\n- Comments cannot currently be edited or deleted after posting',
    updated_at = now()
WHERE slug = 'how-to-use-flow-comments';
