-- KB: Tenant-level account cancellation — two articles (EN + VI)

INSERT INTO knowledge_base (title, slug, content_markdown, category, is_active) VALUES

(
  'How to Cancel Your Aitomic Flow Account',
  'how-to-cancel-account',
  E'# How to Cancel Your Aitomic Flow Account\n\nIf you need to close your Aitomic Flow workspace, you can initiate cancellation from the Settings page. There is a 7-day cooling-off period before any data is deleted, giving you time to download your data or change your mind.\n\n## Who can cancel the account\n\nOnly the **workspace admin** can cancel the account. Regular users do not have access to this option.\n\n## How to cancel\n\n1. Go to **Settings** in the left sidebar\n2. The **General** tab is shown by default\n3. Scroll to the **Danger Zone** section at the bottom\n4. Click **Cancel account**\n5. Read the confirmation dialog carefully — it lists exactly what will be deleted\n6. Click **Yes, cancel my account** to confirm\n\nImmediately after confirming:\n- Your account status changes to "Cancellation scheduled"\n- You receive a confirmation email with your full data export attached (users, flow instances, and departments as CSV files)\n- An amber warning banner appears at the top of the Settings page with the exact deletion date\n\n## The 7-day cooling-off period\n\nYour data is **not deleted immediately**. You have 7 days from the moment you confirm cancellation to reverse the decision. During this time:\n- The workspace continues to function normally\n- All users can still log in and use the system\n- No data is modified or deleted\n\n## How to undo cancellation\n\n1. Go to **Settings → General**\n2. Click **Undo cancellation** in the amber banner at the top\n\nYour account will return to Active status immediately and the deletion will be cancelled. You will receive a confirmation email.\n\nThe undo option disappears after the 7-day window has closed.\n\n## What happens if you do not undo\n\nAfter the 7-day cooling-off period:\n- All user accounts are permanently deleted\n- All workflows, instances, and form data are permanently deleted\n- All departments and organisational data are permanently deleted\n- All attached files and exports are permanently deleted\n\nThis process is **irreversible**. There is no way to recover data after deletion.\n\n## Before you cancel\n\nWe recommend doing the following before the deletion date:\n\n- Download the data export CSV files from your confirmation email\n- Export any important flow instance reports from Admin → Instances\n- Notify your team members that their accounts will be deactivated\n\n## See also\n\n- [What Happens to Your Data After Cancellation](/help/data-after-cancellation)\n- [How to Export Flow Instance Data to CSV](/help/export-instance-data-csv)\n- [How to Deactivate and Reactivate a User](/help/how-to-deactivate-user)',
  'account',
  true
),

(
  'What Happens to Your Data After Cancellation',
  'data-after-cancellation',
  E'# What Happens to Your Data After Cancellation\n\nThis article explains exactly what is deleted, when it is deleted, and what you can do to preserve your data before cancellation.\n\n## Timeline\n\n| Day | Event |\n|-----|-------|\n| Day 0 | Admin confirms cancellation. Data export email sent immediately. 7-day clock starts. |\n| Days 1–6 | Workspace is fully functional. Admin can undo cancellation at any time from Settings. |\n| Day 7 | Cooling-off period expires. Deletion runs automatically within 24 hours. |\n| After deletion | All data is permanently gone. No recovery is possible. |\n\n## What is deleted\n\nEverything in your workspace is permanently deleted:\n\n- **Users** — all user accounts, profiles, and login credentials. Users will be immediately unable to sign in.\n- **Workflows** — all flow definitions, published versions, and configurations.\n- **Flow instances** — all triggered workflow runs, completed steps, and submitted form data.\n- **Attachments** — all files uploaded through workflow form fields.\n- **Departments** — all department structures and org chart data.\n- **Notifications** — all in-app notifications and email logs.\n- **Audit trail** — all admin action logs.\n- **Integrations** — all configured Slack and Teams webhook URLs.\n\n## What you receive before deletion\n\nWhen you confirm cancellation, we immediately email you a data export containing three CSV files:\n\n| File | Contents |\n|------|----------|\n| `users.csv` | All user records: name, email, role, department, status, join date |\n| `flow-instances.csv` | All flow run records: instance ID, status, who triggered it, start and end dates |\n| `departments.csv` | All department records: name, parent department, department head |\n\n**Note:** The CSV export does not include form submission data (the actual answers people typed into workflow forms). To export form data, use Admin → Instances → Export before your deletion date.\n\n## How to export form data before deletion\n\n1. Go to **Admin → Instances** in the sidebar\n2. Use the filters to select the flows and date range you need\n3. Click **Export CSV** (instances mode) to download all form data\n4. Repeat for different flows if needed\n\nSigned download URLs for file attachments expire after 7 days. Download any important attachments before the deletion date.\n\n## Can data be recovered after deletion\n\nNo. Once the deletion runs, the data cannot be recovered. We do not maintain backups of deleted tenant data.\n\nIf you have any concerns before the deletion date, contact us at contact@aitomicflow.com.\n\n## See also\n\n- [How to Cancel Your Account](/help/how-to-cancel-account)\n- [How to Export Flow Instance Data to CSV](/help/export-instance-data-csv)',
  'account',
  true
),

(
  'Cách huỷ tài khoản Aitomic Flow',
  'how-to-cancel-account-vi',
  E'# Cách huỷ tài khoản Aitomic Flow\n\nNếu bạn cần đóng không gian làm việc Aitomic Flow, bạn có thể khởi động quá trình huỷ từ trang Cài đặt. Có 7 ngày để suy nghĩ lại trước khi dữ liệu bị xoá vĩnh viễn.\n\n## Ai có thể huỷ tài khoản\n\nChỉ **quản trị viên không gian làm việc** mới có thể huỷ tài khoản.\n\n## Cách huỷ\n\n1. Vào **Cài đặt** trong thanh bên trái\n2. Tab **Chung** được hiển thị mặc định\n3. Cuộn xuống phần **Vùng nguy hiểm** ở cuối trang\n4. Nhấn **Huỷ tài khoản**\n5. Đọc kỹ hộp thoại xác nhận\n6. Nhấn **Có, huỷ tài khoản của tôi** để xác nhận\n\nSau khi xác nhận:\n- Trạng thái tài khoản chuyển sang "Đã lên lịch huỷ"\n- Bạn nhận được email xác nhận kèm xuất dữ liệu đầy đủ (người dùng, phiên bản quy trình, phòng ban dưới dạng CSV)\n- Banner cảnh báo màu hổ phách xuất hiện ở đầu trang Cài đặt với ngày xoá chính xác\n\n## Thời gian suy nghĩ lại 7 ngày\n\nDữ liệu của bạn **không bị xoá ngay lập tức**. Bạn có 7 ngày để đảo ngược quyết định.\n\n## Cách hoàn tác huỷ\n\n1. Vào **Cài đặt → Chung**\n2. Nhấn **Hoàn tác huỷ** trong banner màu hổ phách ở đầu trang\n\nTài khoản sẽ quay lại trạng thái Hoạt động ngay lập tức.\n\n## Điều gì xảy ra nếu bạn không hoàn tác\n\nSau 7 ngày, tất cả dữ liệu sẽ bị xoá vĩnh viễn và không thể khôi phục.\n\n## Xem thêm\n\n- [Điều gì xảy ra với dữ liệu sau khi huỷ](/help/data-after-cancellation-vi)\n- [Cách xuất dữ liệu phiên bản quy trình ra CSV](/help/export-instance-data-csv-vi)',
  'account',
  true
),

(
  'Dữ liệu của bạn sau khi huỷ tài khoản',
  'data-after-cancellation-vi',
  E'# Dữ liệu của bạn sau khi huỷ tài khoản\n\n## Tiến trình\n\n| Ngày | Sự kiện |\n|------|---------|\n| Ngày 0 | Quản trị viên xác nhận huỷ. Email xuất dữ liệu được gửi ngay. Đồng hồ 7 ngày bắt đầu. |\n| Ngày 1–6 | Không gian làm việc hoạt động bình thường. Quản trị viên có thể hoàn tác bất kỳ lúc nào. |\n| Ngày 7 | Thời gian suy nghĩ lại hết hạn. Xoá chạy tự động trong vòng 24 giờ. |\n| Sau khi xoá | Tất cả dữ liệu biến mất vĩnh viễn. Không thể khôi phục. |\n\n## Những gì bị xoá\n\nMọi thứ trong không gian làm việc của bạn đều bị xoá vĩnh viễn:\n\n- **Người dùng** — tất cả tài khoản, hồ sơ và thông tin đăng nhập\n- **Quy trình** — tất cả định nghĩa quy trình và phiên bản đã xuất bản\n- **Phiên bản quy trình** — tất cả lần chạy, bước đã hoàn thành và dữ liệu biểu mẫu\n- **Tệp đính kèm** — tất cả tệp đã tải lên qua biểu mẫu\n- **Phòng ban** — tất cả cấu trúc phòng ban và sơ đồ tổ chức\n\n## Những gì bạn nhận được trước khi xoá\n\nKhi xác nhận huỷ, chúng tôi gửi ngay email với 3 tệp CSV:\n\n| Tệp | Nội dung |\n|-----|---------|\n| `users.csv` | Tất cả người dùng: tên, email, vai trò, phòng ban, ngày tham gia |\n| `flow-instances.csv` | Tất cả lần chạy quy trình: ID, trạng thái, người kích hoạt, ngày bắt đầu/kết thúc |\n| `departments.csv` | Tất cả phòng ban: tên, phòng ban cha, trưởng phòng |\n\n**Lưu ý:** Xuất CSV không bao gồm dữ liệu biểu mẫu chi tiết. Để xuất dữ liệu biểu mẫu, dùng Quản trị → Phiên bản → Xuất CSV trước ngày xoá.\n\n## Dữ liệu có thể khôi phục sau khi xoá không\n\nKhông. Sau khi xoá, dữ liệu không thể khôi phục.\n\n## Xem thêm\n\n- [Cách huỷ tài khoản](/help/how-to-cancel-account-vi)\n- [Cách xuất dữ liệu phiên bản quy trình ra CSV](/help/export-instance-data-csv-vi)',
  'account',
  true
)

ON CONFLICT (slug) DO NOTHING;
