-- KB: AI features and plan requirements (EN + VI)

INSERT INTO knowledge_base (title, slug, content_markdown, category, is_active) VALUES

(
  'AI Features and Plan Requirements',
  'ai-features-plan-requirements',
  E'# AI Features and Plan Requirements\n\nAitomic Flow includes built-in AI tools that help your team draft content, summarise information, and automate text-heavy steps in your workflows. These features are available on **Pro and Enterprise plans** only.\n\n## What AI features include\n\n- AI-assisted text generation inside workflow form steps\n- Automatic summarisation of completed workflow instances\n- Any future AI-powered automation added to the platform\n\n## Who can enable AI\n\nOnly the **workspace admin** can turn AI on or off. Individual users cannot change this setting.\n\n## How to enable AI (Pro and Enterprise plans)\n\n1. Go to **Settings** in the left sidebar\n2. Click the **AI** tab\n3. Toggle **Enable AI features** to on\n4. Choose your AI provider (Anthropic Claude or OpenAI GPT)\n5. Select a model\n6. Choose whether to use the platform API key (billed against your credit quota) or your own API key\n\n## Why the toggle is disabled\n\nIf you see the message *"AI features are not available on the Free plan"* and the toggle is greyed out, your workspace is on the Free plan.\n\nTo enable AI:\n1. Go to **Settings → Billing**\n2. Upgrade to Pro or Enterprise\n3. Return to **Settings → AI** — the toggle will now be active\n\n## Free plan limits\n\nThe Free plan does not include AI features. All other Free plan limits (users, flows, departments) are documented in the Billing section of Settings.\n\n## Credit usage\n\nWhen using the platform API key, AI calls are billed against your organisation\'s monthly credit quota. The current usage is shown in Settings → AI as a progress bar.\n\nIf your credit is exhausted before the reset date, AI calls will fail until the quota resets or you switch to your own API key.\n\n## Using your own API key\n\nYou can bring your own Anthropic or OpenAI API key to bypass the platform credit quota entirely. Usage is then billed directly to your API account.\n\n1. In Settings → AI, turn on **Enable AI features**\n2. Under **API Key Source**, select **Your own key**\n3. Paste your API key and click **Save**\n\nTo remove your key and switch back to the platform key, click **Remove** next to the masked key.\n\n## See also\n\n- [Understanding Your Billing Plan](/help/billing-plan-overview)\n- [How to Export Flow Instance Data to CSV](/help/export-instance-data-csv)',
  'technical',
  true
),

(
  'Tính năng AI và yêu cầu gói dịch vụ',
  'ai-features-plan-requirements-vi',
  E'# Tính năng AI và yêu cầu gói dịch vụ\n\nAitomic Flow tích hợp các công cụ AI giúp nhóm của bạn soạn thảo nội dung, tóm tắt thông tin và tự động hoá các bước trong quy trình. Các tính năng này chỉ có trên **gói Pro và Enterprise**.\n\n## Tính năng AI bao gồm những gì\n\n- Tạo văn bản hỗ trợ bởi AI trong các bước biểu mẫu quy trình\n- Tóm tắt tự động các phiên bản quy trình đã hoàn thành\n- Các tính năng tự động hoá AI sẽ được bổ sung trong tương lai\n\n## Ai có thể bật AI\n\nChỉ **quản trị viên không gian làm việc** mới có thể bật hoặc tắt AI.\n\n## Cách bật AI (gói Pro và Enterprise)\n\n1. Vào **Cài đặt** trong thanh bên trái\n2. Nhấn tab **AI**\n3. Bật nút **Bật tính năng AI**\n4. Chọn nhà cung cấp AI (Anthropic Claude hoặc OpenAI GPT)\n5. Chọn mô hình\n6. Chọn dùng khoá API của nền tảng (tính vào hạn mức tín dụng) hay khoá API riêng của bạn\n\n## Tại sao nút bật/tắt bị vô hiệu hoá\n\nNếu bạn thấy thông báo *"Tính năng AI không có trên gói Free"* và nút bị mờ, không gian làm việc của bạn đang dùng gói Free.\n\nĐể bật AI:\n1. Vào **Cài đặt → Thanh toán**\n2. Nâng cấp lên gói Pro hoặc Enterprise\n3. Quay lại **Cài đặt → AI** — nút sẽ hoạt động\n\n## Hạn mức tín dụng\n\nKhi dùng khoá API của nền tảng, các lần gọi AI sẽ được tính vào hạn mức tín dụng hàng tháng. Mức sử dụng hiện tại hiển thị trong Cài đặt → AI dưới dạng thanh tiến trình.\n\n## Dùng khoá API riêng\n\nBạn có thể dùng khoá API Anthropic hoặc OpenAI của riêng mình để không bị giới hạn bởi hạn mức của nền tảng.\n\n1. Trong Cài đặt → AI, bật **Bật tính năng AI**\n2. Trong **Nguồn khoá API**, chọn **Khoá của bạn**\n3. Dán khoá API và nhấn **Lưu**\n\n## Xem thêm\n\n- [Tổng quan về gói thanh toán](/help/billing-plan-overview-vi)\n- [Cách xuất dữ liệu phiên bản quy trình ra CSV](/help/export-instance-data-csv-vi)',
  'technical',
  true
)

ON CONFLICT (slug) DO NOTHING;
