-- KB: Getting started as a new team member (EN + VI)
-- Covers the non-admin first-session experience: accepting an invite,
-- completing the first task, and finding flows to trigger.

INSERT INTO knowledge_base (title, slug, content_markdown, category, is_active) VALUES

(
  'Getting Started as a New Team Member',
  'getting-started-as-a-team-member',
  E'# Getting Started as a New Team Member\n\nThis guide is for people who have received an invitation to join an Aitomic Flow workspace — not for the admin who set it up.\n\n## Step 1: Accept your invitation\n\nYou will receive an email with the subject "You''ve been invited to join [Organisation] on Aitomic Flow". Click the **Accept invitation** button in the email.\n\nThe link is valid for **24 hours**. If it has expired, ask your admin to resend it from the Pending Invitations page.\n\nYou will be taken to a setup page where you enter your full name and create a password. Once submitted, you are logged in and taken to your Tasks page.\n\n## Step 2: Complete your profile (optional)\n\nGo to your avatar in the top-right corner → **Settings** to add a profile photo, job title, and phone number. This information is visible to your colleagues in the User Directory and Org Chart.\n\n## Step 3: Check your Pending Tasks\n\nThe **Tasks** page (/tasks) is your home base. The **Pending** tab shows steps currently assigned to you. If a workflow has already been triggered and a step is waiting for you, it will appear here.\n\nClick **Open** on any task to see the form, fill it in, and click **Submit** to complete your part and move the workflow forward.\n\n## Step 4: Start a flow yourself\n\nThe **Flows** page (/flows) lists all published workflows that are available for you to trigger. Click **Start** on any flow to kick off a new instance — for example, to submit a leave request, expense claim, or purchase order.\n\nAfter triggering a flow, you can track its progress under **Tasks → My Flows**.\n\n## What happens after you submit a step\n\nWhen you submit a step:\n\n- The workflow engine automatically advances to the next step and assigns it to the appropriate person\n- You receive an in-app notification (bell icon, top-right) and optionally an email when the overall flow completes\n- The completed step moves from your Pending list to your History\n\n## Notifications\n\nThe bell icon in the top-right shows unread notifications. You will be notified when:\n\n- A new step is assigned to you\n- A flow you triggered completes\n- Someone comments on a flow instance you are part of\n\nClick any notification to go directly to the relevant task or flow.\n\n## See also\n\n- [How to Complete a Task](/help/how-to-complete-task)\n- [How to Start a Workflow](/help/how-to-start-workflow)\n- [Understanding Notifications](/help/understanding-notifications)',
  'how-to',
  true
),

(
  'Bắt đầu với tư cách thành viên nhóm mới',
  'getting-started-as-a-team-member-vi',
  E'# Bắt đầu với tư cách thành viên nhóm mới\n\nHướng dẫn này dành cho những người đã nhận được lời mời tham gia không gian làm việc Aitomic Flow — không phải cho quản trị viên đã thiết lập.\n\n## Bước 1: Chấp nhận lời mời\n\nBạn sẽ nhận được email với tiêu đề "Bạn được mời tham gia [Tổ chức] trên Aitomic Flow". Nhấp vào nút **Chấp nhận lời mời** trong email.\n\nLiên kết có hiệu lực trong **24 giờ**. Nếu hết hạn, hãy yêu cầu quản trị viên gửi lại từ trang Lời mời đang chờ.\n\nBạn sẽ được đưa đến trang thiết lập để nhập tên đầy đủ và tạo mật khẩu. Sau khi gửi, bạn được đăng nhập và chuyển đến trang Công việc.\n\n## Bước 2: Hoàn thiện hồ sơ (tùy chọn)\n\nVào avatar góc trên bên phải → **Cài đặt** để thêm ảnh đại diện, chức danh và số điện thoại.\n\n## Bước 3: Kiểm tra công việc đang chờ\n\nTrang **Công việc** (/tasks) là trang chủ của bạn. Tab **Đang chờ** hiển thị các bước hiện đang được giao cho bạn.\n\nNhấp **Mở** trên bất kỳ công việc nào để xem biểu mẫu, điền vào và nhấp **Gửi** để hoàn thành phần của bạn.\n\n## Bước 4: Tự kích hoạt quy trình\n\nTrang **Quy trình** (/flows) liệt kê tất cả quy trình đã xuất bản mà bạn có thể kích hoạt. Nhấn **Bắt đầu** trên bất kỳ quy trình nào để tạo phiên bản mới.\n\nSau khi kích hoạt quy trình, bạn có thể theo dõi tiến trình trong **Công việc → Quy trình của tôi**.\n\n## Điều gì xảy ra sau khi bạn gửi một bước\n\nKhi bạn gửi bước:\n\n- Engine quy trình tự động chuyển sang bước tiếp theo và phân công cho người phù hợp\n- Bạn nhận được thông báo trong ứng dụng khi toàn bộ quy trình hoàn thành\n- Bước đã hoàn thành chuyển từ danh sách Đang chờ sang Lịch sử\n\n## Thông báo\n\nBiểu tượng chuông góc trên bên phải hiển thị thông báo chưa đọc. Bạn sẽ được thông báo khi:\n\n- Một bước mới được giao cho bạn\n- Quy trình bạn đã kích hoạt hoàn thành\n- Ai đó bình luận trên phiên bản quy trình mà bạn tham gia\n\n## Xem thêm\n\n- [Cách hoàn thành một công việc](/help/how-to-complete-task-vi)\n- [Cách bắt đầu quy trình làm việc](/help/how-to-start-workflow-vi)\n- [Tìm hiểu thông báo](/help/understanding-notifications-vi)',
  'how-to',
  true
)

ON CONFLICT (slug) DO NOTHING;
