-- KB: 8 flow lifecycle & operational articles (EN + VI = 16 rows)
-- Topics: draft/published state, instance statuses, editing running flows,
-- cancelling an instance, reassigning a step, flow not visible, CSV export,
-- SLA calendar-hour calculation.
-- These cover the highest-risk AI hallucination gaps: app-specific behaviours
-- that differ from general workflow-tool knowledge.

INSERT INTO knowledge_base (title, slug, content_markdown, category, is_active) VALUES

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. Flow Draft vs Published
-- ═══════════════════════════════════════════════════════════════════════════

(
  'Flow Draft vs Published: Why Can''t I Trigger My Flow?',
  'flow-draft-vs-published',
  E'# Flow Draft vs Published: Why Can''t I Trigger My Flow?\n\nEvery flow in Aitomic Flow exists in one of two states: **Draft** or **Published**. Only published flows can be triggered. This is the most common reason a flow cannot be started.\n\n## Draft state\n\nA flow is in Draft when you first create it or any time you make changes after publishing. In Draft:\n\n- The flow is visible only to admins inside the Flow Builder\n- It **cannot be triggered** by anyone, including admins\n- You can freely edit steps, form fields, branch conditions, and assignee rules\n- The flow does not appear in the trigger list on the /flows page for any user\n\nA newly created flow is always a draft. You must explicitly publish it before anyone can use it.\n\n## Published state\n\nWhen you click **Publish**, the flow:\n\n- Becomes visible on the /flows page for all eligible users\n- Can be triggered by users whose department is allowed (if trigger restrictions are configured)\n- Gets a new version number — version 1 for first publish, then 2, 3, and so on\n\nPublishing is non-destructive. Any instances already running are not affected.\n\n## How to publish a flow\n\n1. Open the flow in the builder\n2. Click the **Publish** panel in the top-right toolbar\n3. Click **Publish** to confirm\n\nIf the Publish button is disabled, the flow has a validation error — most commonly a Branch node with an unconnected Yes or No handle.\n\n## Unpublishing a flow\n\nAdmins can unpublish a flow from the Publish panel. After unpublishing:\n\n- The flow returns to Draft and no new instances can be triggered\n- Existing running instances are **not cancelled** — they continue to completion on the version they started\n\n## Why a published flow might still not appear for a user\n\nEven after publishing, a specific user might not see the flow because:\n\n1. **Trigger restrictions** — the flow has a department allowlist and the user''s department is not on it\n2. **No department assigned** — the user has no department and the flow is restricted to specific departments\n3. **Deactivated account** — an inactive account cannot see or trigger flows\n\nSee [Why a Flow Is Not Visible or Not Available to Trigger](/help/why-flow-not-visible).\n\n## See also\n\n- [How to Create a Workflow](/help/how-to-create-workflow)\n- [Understanding Workflow Versions](/help/understanding-workflow-versions)\n- [Why a Flow Is Not Visible or Not Available to Trigger](/help/why-flow-not-visible)',
  'how-to',
  true
),

(
  'Trạng thái Bản nháp và Đã xuất bản: Tại sao tôi không thể kích hoạt quy trình?',
  'flow-draft-vs-published-vi',
  E'# Trạng thái Bản nháp và Đã xuất bản: Tại sao tôi không thể kích hoạt quy trình?\n\nMỗi quy trình trong Aitomic Flow tồn tại ở một trong hai trạng thái: **Bản nháp** hoặc **Đã xuất bản**. Chỉ các quy trình đã xuất bản mới có thể được kích hoạt. Đây là lý do phổ biến nhất khiến một quy trình không thể được bắt đầu.\n\n## Trạng thái Bản nháp\n\nQuy trình ở trạng thái Bản nháp khi bạn mới tạo hoặc sau khi thực hiện thay đổi sau khi xuất bản. Ở trạng thái Bản nháp:\n\n- Quy trình chỉ hiển thị với quản trị viên trong Trình tạo quy trình\n- **Không thể kích hoạt** bởi bất kỳ ai, kể cả quản trị viên\n- Bạn có thể tự do chỉnh sửa các bước, trường biểu mẫu, điều kiện rẽ nhánh và quy tắc phân công\n- Quy trình không xuất hiện trong danh sách kích hoạt trên trang /flows\n\nQuy trình mới tạo luôn ở trạng thái Bản nháp. Bạn phải xuất bản thủ công trước khi ai đó có thể sử dụng.\n\n## Trạng thái Đã xuất bản\n\nKhi bạn nhấn **Xuất bản**, quy trình sẽ:\n\n- Hiển thị trên trang /flows cho tất cả người dùng đủ điều kiện\n- Có thể được kích hoạt bởi người dùng thuộc phòng ban được phép (nếu có hạn chế kích hoạt)\n- Nhận số phiên bản mới — phiên bản 1 lần xuất bản đầu tiên, sau đó là 2, 3, v.v.\n\nXuất bản không ảnh hưởng đến các phiên bản đang chạy.\n\n## Cách xuất bản quy trình\n\n1. Mở quy trình trong trình tạo\n2. Nhấp vào bảng **Xuất bản** ở góc trên bên phải\n3. Nhấn **Xuất bản** để xác nhận\n\nNếu nút Xuất bản bị vô hiệu hóa, quy trình có lỗi xác thực — thường nhất là nút Branch thiếu kết nối trên đầu ra Có hoặc Không.\n\n## Hủy xuất bản quy trình\n\nQuản trị viên có thể hủy xuất bản quy trình từ bảng Xuất bản. Sau khi hủy xuất bản:\n\n- Quy trình trở về Bản nháp và không thể kích hoạt phiên bản mới\n- Các phiên bản đang chạy **không bị hủy** — chúng tiếp tục đến hoàn thành\n\n## Tại sao quy trình đã xuất bản vẫn không hiển thị với người dùng\n\n1. **Hạn chế kích hoạt** — quy trình có danh sách phòng ban được phép và phòng ban của người dùng không có trong danh sách\n2. **Chưa có phòng ban** — người dùng chưa được gán phòng ban và quy trình bị hạn chế\n3. **Tài khoản bị vô hiệu hóa** — tài khoản không hoạt động không thể xem hoặc kích hoạt quy trình\n\n## Xem thêm\n\n- [Cách tạo quy trình làm việc](/help/how-to-create-workflow-vi)\n- [Tại sao quy trình không hiển thị với người dùng](/help/why-flow-not-visible-vi)',
  'how-to',
  true
),

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. Understanding Flow Instance Statuses
-- ═══════════════════════════════════════════════════════════════════════════

(
  'Understanding Flow Instance Statuses',
  'flow-instance-statuses',
  E'# Understanding Flow Instance Statuses\n\nWhen a flow is triggered, an **instance** is created to track that specific run from start to finish. Every instance has a status that tells you where it is in its lifecycle.\n\n## Pending\n\nThe instance is active and in progress. At least one step is currently assigned and waiting for someone to complete it.\n\nThis is the normal state for flows that have been started but not yet finished. Most instances spend the majority of their lifetime in Pending.\n\n## Completed\n\nThe instance reached a **Complete** node on the canvas. All required steps on the path have been submitted. No further action is needed.\n\nCompleted instances are read-only. The full step history, submitted form data, and uploaded files remain accessible indefinitely.\n\n## Cancelled\n\nAn admin manually cancelled the instance. No new steps will be created or assigned. Cancellation is permanent — a cancelled instance cannot be resumed.\n\nPending steps that existed at the time of cancellation remain in the history but require no action.\n\n## Error\n\nThe workflow engine encountered a problem it could not automatically resolve. The most common cause is an **assignee resolution failure** — the assignee rule for a step could not find a valid user. Examples:\n\n- "Manager of Requestor" rule: the person who triggered the flow has no manager assigned\n- "Fixed assignee" rule: the designated user has been deactivated\n- "Department head" rule: the target department has no head assigned\n- "Role in department" rule: no active users with the required role exist in the department\n\nWhen an error occurs, the instance stops progressing. An error event is logged in the activity log with a description of the failure.\n\n## What to do when you see an Error status\n\n1. Open the instance in **Admin → Instances**\n2. Read the **Activity Log** — the error event describes which step failed and why\n3. Fix the root cause (assign a manager, reactivate the fixed assignee, assign a department head, etc.)\n4. **Re-trigger the flow** — a flow in Error cannot be automatically resumed; the requester must start a new instance\n\n## Where to check instance statuses\n\n- **My Flows tab** (/tasks → My Flows) — instances you triggered\n- **Admin → Instances** — all instances in your organisation, with a status filter\n- **Instance detail panel** — click any instance row to see the full history and current status\n\n## See also\n\n- [What to Do If a Workflow Step Is Stuck or Errors](/help/workflow-step-stuck-or-error)\n- [All Assignee Rule Types Explained](/help/assignee-rule-types-reference)\n- [How to Cancel a Running Flow Instance](/help/how-to-cancel-a-flow-instance)',
  'technical',
  true
),

(
  'Tìm hiểu các trạng thái phiên bản quy trình',
  'flow-instance-statuses-vi',
  E'# Tìm hiểu các trạng thái phiên bản quy trình\n\nKhi một quy trình được kích hoạt, một **phiên bản** được tạo để theo dõi lần chạy đó từ đầu đến cuối. Mỗi phiên bản có trạng thái cho biết nó đang ở đâu trong vòng đời.\n\n## Đang xử lý (Pending)\n\nPhiên bản đang hoạt động và tiến triển. Ít nhất một bước hiện đang được giao và chờ ai đó hoàn thành.\n\nĐây là trạng thái bình thường của quy trình đã được bắt đầu nhưng chưa kết thúc.\n\n## Đã hoàn thành (Completed)\n\nPhiên bản đã đến nút **Complete** trên canvas. Tất cả các bước bắt buộc trên đường dẫn đã được gửi. Không cần thêm hành động nào.\n\nCác phiên bản đã hoàn thành ở chế độ chỉ đọc. Toàn bộ lịch sử bước, dữ liệu biểu mẫu đã gửi và tệp tải lên vẫn có thể truy cập.\n\n## Đã hủy (Cancelled)\n\nMột quản trị viên đã hủy phiên bản thủ công. Không có bước mới nào được tạo hoặc phân công. Việc hủy là vĩnh viễn — phiên bản đã hủy không thể tiếp tục.\n\n## Lỗi (Error)\n\nEngine quy trình gặp sự cố không thể tự động giải quyết. Nguyên nhân phổ biến nhất là **lỗi phân giải người nhận** — quy tắc phân công cho một bước không tìm thấy người dùng hợp lệ. Ví dụ:\n\n- Quy tắc "Quản lý của người yêu cầu": người kích hoạt chưa được gán quản lý\n- Quy tắc "Người nhận cố định": người được chỉ định đã bị vô hiệu hóa\n- Quy tắc "Trưởng phòng ban": phòng ban mục tiêu chưa có trưởng phòng\n\nKhi xảy ra lỗi, phiên bản ngừng tiến triển. Sự kiện lỗi được ghi vào nhật ký hoạt động.\n\n## Phải làm gì khi thấy trạng thái Lỗi\n\n1. Mở phiên bản trong **Quản trị → Phiên bản**\n2. Đọc **Nhật ký hoạt động** — sự kiện lỗi mô tả bước nào thất bại và tại sao\n3. Sửa nguyên nhân gốc rễ (gán quản lý, kích hoạt lại người nhận cố định, v.v.)\n4. **Kích hoạt lại quy trình** — quy trình bị lỗi không thể tự động tiếp tục; người yêu cầu phải bắt đầu phiên bản mới\n\n## Xem thêm\n\n- [Phải làm gì khi bước quy trình bị kẹt hoặc lỗi](/help/workflow-step-stuck-or-error-vi)\n- [Giải thích tất cả loại quy tắc phân công](/help/assignee-rule-types-reference-vi)\n- [Cách hủy phiên bản quy trình đang chạy](/help/how-to-cancel-a-flow-instance-vi)',
  'technical',
  true
),

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. What Happens to Running Flows When You Edit and Republish
-- ═══════════════════════════════════════════════════════════════════════════

(
  'What Happens to Running Flows When You Edit and Republish',
  'flow-editing-and-active-instances',
  E'# What Happens to Running Flows When You Edit and Republish\n\nIf you edit a published flow and republish it, existing running instances are **never affected**. This is one of the most important things to understand about how Aitomic Flow versioning works.\n\n## How versioning protects running instances\n\nEvery time you publish a flow, Aitomic Flow creates a new version number (1, 2, 3, …). Each flow instance is permanently linked to the version that was active at the moment it was triggered.\n\n- **Existing instances** continue running on the version they started. They see the original steps, branch conditions, and form fields exactly as they were when triggered.\n- **New instances** triggered after the republish use the new version.\n\nThis behaviour is intentional. Changing rules mid-flight for a running instance would produce unpredictable results — a step a user already completed might suddenly require new fields, or a branch might route differently.\n\n## Practical examples\n\n**You add a new required field to an Action step**\n\nInstances already triggered will not see the new field. Only new instances will have it. If all instances must capture this data, wait for current ones to finish before publishing the change, or handle it via a separate process for in-flight work.\n\n**You fix a branch condition**\n\nThe fix applies to new instances only. If an existing instance has already passed the branch node or is stuck because of the old condition, the fix does not retroactively correct it. Consider cancelling the stuck instance and asking the requester to re-trigger.\n\n**You rename a step or change a description**\n\nCosmetic changes do not affect running instances — old instances display the original name in their history.\n\n## Checking which version an instance is running\n\nOpen the instance detail (Admin → Instances → click an instance). The header shows the version number and flow name, confirming which published version is in use.\n\n## Unpublishing does not cancel running instances\n\nIf you unpublish a flow (return it to Draft), all running instances continue to completion on the version they started. Unpublishing only blocks new triggers.\n\n## See also\n\n- [Understanding Workflow Versions](/help/understanding-workflow-versions)\n- [Flow Draft vs Published](/help/flow-draft-vs-published)\n- [Understanding Flow Instance Statuses](/help/flow-instance-statuses)',
  'technical',
  true
),

(
  'Điều gì xảy ra với quy trình đang chạy khi bạn chỉnh sửa và xuất bản lại',
  'flow-editing-and-active-instances-vi',
  E'# Điều gì xảy ra với quy trình đang chạy khi bạn chỉnh sửa và xuất bản lại\n\nNếu bạn chỉnh sửa quy trình đã xuất bản và xuất bản lại, các phiên bản đang chạy **không bao giờ bị ảnh hưởng**. Đây là một trong những điều quan trọng nhất cần hiểu về cách phiên bản hóa trong Aitomic Flow hoạt động.\n\n## Cách phiên bản hóa bảo vệ các phiên bản đang chạy\n\nMỗi khi bạn xuất bản quy trình, Aitomic Flow tạo ra số phiên bản mới (1, 2, 3, …). Mỗi phiên bản quy trình được liên kết vĩnh viễn với phiên bản đang hoạt động tại thời điểm kích hoạt.\n\n- **Phiên bản hiện có** tiếp tục chạy trên phiên bản đã bắt đầu. Chúng thấy các bước, điều kiện rẽ nhánh và trường biểu mẫu gốc chính xác như khi được kích hoạt.\n- **Phiên bản mới** được kích hoạt sau khi xuất bản lại sử dụng phiên bản mới.\n\nHành vi này là có chủ ý. Thay đổi quy tắc giữa chừng cho phiên bản đang chạy sẽ tạo ra kết quả không thể đoán trước.\n\n## Ví dụ thực tế\n\n**Bạn thêm trường bắt buộc mới vào bước Action**\n\nCác phiên bản đã kích hoạt sẽ không thấy trường mới. Chỉ phiên bản mới mới có nó.\n\n**Bạn sửa điều kiện rẽ nhánh**\n\nBản sửa lỗi chỉ áp dụng cho phiên bản mới. Nếu phiên bản hiện có bị kẹt vì điều kiện cũ, hãy hủy phiên bản đó và yêu cầu người dùng kích hoạt lại.\n\n**Hủy xuất bản không hủy phiên bản đang chạy**\n\nNếu bạn hủy xuất bản quy trình, tất cả phiên bản đang chạy tiếp tục đến hoàn thành. Hủy xuất bản chỉ chặn các kích hoạt mới.\n\n## Xem thêm\n\n- [Tìm hiểu phiên bản quy trình](/help/understanding-workflow-versions-vi)\n- [Trạng thái Bản nháp và Đã xuất bản](/help/flow-draft-vs-published-vi)\n- [Tìm hiểu các trạng thái phiên bản quy trình](/help/flow-instance-statuses-vi)',
  'technical',
  true
),

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. How to Cancel a Running Flow Instance
-- ═══════════════════════════════════════════════════════════════════════════

(
  'How to Cancel a Running Flow Instance',
  'how-to-cancel-a-flow-instance',
  E'# How to Cancel a Running Flow Instance\n\nAdmins can cancel a flow instance at any time. Cancellation is permanent — a cancelled instance cannot be resumed or restarted from where it stopped.\n\n## Who can cancel\n\nOnly **admins** can cancel flow instances. Regular users cannot cancel flows, even ones they triggered themselves.\n\n## How to cancel\n\n1. Go to **Admin → Instances** in the left sidebar\n2. Find the instance to cancel — use filters (flow name, status, triggered-by user, date range) or the search box if needed\n3. Click the instance row to open the detail panel\n4. Click the **Cancel** button at the top of the detail panel\n5. Confirm the cancellation in the dialog\n\nThe instance status immediately changes to **Cancelled**.\n\n## What happens after cancellation\n\n- The instance is permanently closed — no new steps will be created or assigned\n- Steps that were **Pending** at the time of cancellation remain in the history but require no action\n- Assigned users for those pending steps are **not automatically notified** of the cancellation — notify them manually if appropriate\n- All previously submitted form data and uploaded files remain accessible in the instance history\n\n## When to cancel a flow\n\n**Common reasons:**\n\n- The flow was triggered by mistake or was a test run\n- The underlying request has been withdrawn or superseded by another instance\n- The instance is in **Error** status and cannot be recovered — cancel it and ask the requester to re-trigger a new instance\n- Duplicate instances exist for the same request\n\n## Cancellation vs letting the flow finish\n\nIf you simply want the workflow to conclude, the better option is usually to let the current step assignee complete or reject it normally. Cancellation is a hard stop.\n\nIf a step is stuck because the assignee is unavailable, consider **reassigning the step** instead of cancelling the entire flow.\n\n## See also\n\n- [How to Reassign a Pending Step to Another User](/help/how-to-reassign-a-pending-step)\n- [Understanding Flow Instance Statuses](/help/flow-instance-statuses)\n- [What to Do If a Workflow Step Is Stuck or Errors](/help/workflow-step-stuck-or-error)',
  'how-to',
  true
),

(
  'Cách hủy phiên bản quy trình đang chạy',
  'how-to-cancel-a-flow-instance-vi',
  E'# Cách hủy phiên bản quy trình đang chạy\n\nQuản trị viên có thể hủy phiên bản quy trình bất kỳ lúc nào. Việc hủy là vĩnh viễn — phiên bản đã hủy không thể tiếp tục hoặc khởi động lại từ chỗ dừng.\n\n## Ai có thể hủy\n\nChỉ **quản trị viên** mới có thể hủy phiên bản quy trình. Người dùng thông thường không thể hủy quy trình, kể cả quy trình do chính họ kích hoạt.\n\n## Cách hủy\n\n1. Vào **Quản trị → Phiên bản** trong thanh bên\n2. Tìm phiên bản cần hủy — dùng bộ lọc hoặc tìm kiếm nếu cần\n3. Nhấp vào hàng phiên bản để mở bảng chi tiết\n4. Nhấn nút **Hủy** ở đầu bảng chi tiết\n5. Xác nhận việc hủy trong hộp thoại\n\nTrạng thái phiên bản ngay lập tức chuyển thành **Đã hủy**.\n\n## Điều gì xảy ra sau khi hủy\n\n- Phiên bản bị đóng vĩnh viễn — không có bước mới nào được tạo hoặc phân công\n- Các bước **Đang xử lý** tại thời điểm hủy vẫn còn trong lịch sử nhưng không cần thao tác\n- Người dùng được giao các bước đó **không tự động nhận thông báo** về việc hủy\n- Tất cả dữ liệu biểu mẫu đã gửi và tệp tải lên vẫn có thể truy cập trong lịch sử phiên bản\n\n## Khi nào nên hủy quy trình\n\n- Quy trình được kích hoạt nhầm hoặc chỉ là thử nghiệm\n- Yêu cầu cơ bản đã bị rút lại hoặc thay thế bởi phiên bản khác\n- Phiên bản ở trạng thái **Lỗi** và không thể khôi phục\n- Tồn tại các phiên bản trùng lặp cho cùng một yêu cầu\n\n## Xem thêm\n\n- [Cách chuyển giao bước đang xử lý cho người dùng khác](/help/how-to-reassign-a-pending-step-vi)\n- [Tìm hiểu các trạng thái phiên bản quy trình](/help/flow-instance-statuses-vi)\n- [Phải làm gì khi bước quy trình bị kẹt hoặc lỗi](/help/workflow-step-stuck-or-error-vi)',
  'how-to',
  true
),

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. How to Reassign a Pending Step to Another User
-- ═══════════════════════════════════════════════════════════════════════════

(
  'How to Reassign a Pending Step to Another User',
  'how-to-reassign-a-pending-step',
  E'# How to Reassign a Pending Step to Another User\n\nIf a pending step is assigned to the wrong person, or the original assignee is unavailable, an admin can reassign it to a different active user at any time.\n\n## Who can reassign\n\nOnly **admins** can reassign pending steps. Regular users cannot reassign steps, even ones assigned to themselves.\n\n## How to reassign a single step\n\n1. Go to **Admin → Instances** in the sidebar\n2. Find and open the relevant flow instance\n3. In the detail panel, locate the step showing as **Pending**\n4. Click the **Reassign** button next to that step\n5. Select the new assignee from the dropdown — only active users in your organisation are shown\n6. Confirm — the new assignee receives an in-app notification\n\nThe step remains Pending but is now assigned to the new user. It disappears from the original assignee''s task list and appears in the new assignee''s.\n\n## How to bulk reassign all tasks from one user\n\nIf a user is leaving or has been deactivated, you can move all their pending tasks at once:\n\n1. Go to **Users** in the sidebar and open the user''s profile page\n2. If the user has pending tasks, a **Reassign N pending tasks** button appears\n3. Click it, choose the new assignee, and confirm\n\nThis transfers every pending step_instance assigned to that user to the new assignee in a single operation and logs the action in the audit trail.\n\nBulk reassign is also offered automatically inside the **Deactivate User** guided workflow — if you deactivate a user who has open tasks, you are prompted to reassign them as part of the offboarding steps.\n\n## What happens to the original assignee\n\nThe step is removed from the original assignee''s Pending Tasks list immediately. They are not automatically notified — consider informing them manually if appropriate.\n\n## See also\n\n- [How to Deactivate and Reactivate a User](/help/how-to-deactivate-user)\n- [How to Cancel a Running Flow Instance](/help/how-to-cancel-a-flow-instance)\n- [Understanding Flow Instance Statuses](/help/flow-instance-statuses)',
  'how-to',
  true
),

(
  'Cách chuyển giao bước đang xử lý cho người dùng khác',
  'how-to-reassign-a-pending-step-vi',
  E'# Cách chuyển giao bước đang xử lý cho người dùng khác\n\nNếu bước đang xử lý được giao cho sai người hoặc người nhận ban đầu không có sẵn, quản trị viên có thể chuyển giao cho người dùng đang hoạt động khác bất kỳ lúc nào.\n\n## Ai có thể chuyển giao\n\nChỉ **quản trị viên** mới có thể chuyển giao bước đang xử lý. Người dùng thông thường không thể chuyển giao bước, kể cả bước được giao cho chính họ.\n\n## Cách chuyển giao một bước\n\n1. Vào **Quản trị → Phiên bản** trong thanh bên\n2. Tìm và mở phiên bản quy trình liên quan\n3. Trong bảng chi tiết, tìm bước đang hiển thị **Đang xử lý**\n4. Nhấn nút **Chuyển giao** bên cạnh bước đó\n5. Chọn người nhận mới từ danh sách thả xuống — chỉ hiển thị người dùng đang hoạt động\n6. Xác nhận — người nhận mới nhận được thông báo trong ứng dụng\n\nBước vẫn ở trạng thái Đang xử lý nhưng giờ được giao cho người dùng mới.\n\n## Cách chuyển giao hàng loạt tất cả công việc của một người dùng\n\nNếu một người dùng sắp nghỉ hoặc đã bị vô hiệu hóa, bạn có thể chuyển tất cả công việc đang xử lý của họ cùng một lúc:\n\n1. Vào **Người dùng** trong thanh bên và mở trang hồ sơ của người dùng\n2. Nếu người dùng có công việc đang xử lý, nút **Chuyển giao N công việc đang xử lý** sẽ xuất hiện\n3. Nhấn vào đó, chọn người nhận mới và xác nhận\n\nThao tác này chuyển mọi bước đang xử lý được giao cho người dùng đó sang người nhận mới trong một thao tác duy nhất và ghi lại hành động trong nhật ký kiểm toán.\n\nChuyển giao hàng loạt cũng được cung cấp tự động trong quy trình **Vô hiệu hóa người dùng** — nếu bạn vô hiệu hóa người dùng có công việc đang mở, bạn sẽ được nhắc chuyển giao chúng.\n\n## Xem thêm\n\n- [Cách vô hiệu hóa và kích hoạt lại người dùng](/help/how-to-deactivate-user-vi)\n- [Cách hủy phiên bản quy trình đang chạy](/help/how-to-cancel-a-flow-instance-vi)',
  'how-to',
  true
),

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. Why a Flow Is Not Visible or Not Available to Trigger
-- ═══════════════════════════════════════════════════════════════════════════

(
  'Why a Flow Is Not Visible or Not Available to Trigger',
  'why-flow-not-visible',
  E'# Why a Flow Is Not Visible or Not Available to Trigger\n\nIf a user cannot see a flow in their list or cannot trigger it, one of the following reasons usually applies. Work through them in order.\n\n## Reason 1: The flow is in Draft\n\nA flow must be **published** before it appears in the /flows trigger list. Draft flows are visible only to admins inside the Flow Builder.\n\n**How to check:** Open the flow in the builder. The Publish panel in the top-right will show Draft or the current published version number.\n\n**How to fix:** Click Publish in the Publish panel.\n\nSee [Flow Draft vs Published](/help/flow-draft-vs-published) for full detail.\n\n## Reason 2: Trigger restrictions — user''s department is not allowed\n\nA flow can be restricted to specific departments. If the user''s department is not on the allowed list, the flow will not appear in their trigger list at all — it is as if it does not exist for them.\n\n**How to check:** Open the flow builder → Publish panel → Trigger Restrictions section. If departments are listed, only users in those departments can see and trigger the flow.\n\n**How to fix:** Add the user''s department to the allowed list, or move the user to an allowed department.\n\n## Reason 3: The user has no department assigned\n\nIf a flow has trigger restrictions and the user has no department assigned, they will not match any entry in the allowed list.\n\n**How to check:** Open the user''s profile in Users — look at the Department field.\n\n**How to fix:** Assign the user to the relevant department via their profile or via the Departments management page.\n\n## Reason 4: The user account is deactivated\n\nAn inactive (deactivated) account cannot see or trigger any flows.\n\n**How to check:** Open the user''s profile page. An amber **Inactive** banner appears at the top if deactivated.\n\n**How to fix:** Click Reactivate on the user''s profile page.\n\n## Reason 5: The user is looking in the wrong place\n\nFlows available to trigger are listed on the **/flows** page (accessible from the "Flows" item in the left sidebar). The /tasks page → My Flows tab shows instances the user has **already triggered** — it does not show flows available to start.\n\n**How to fix:** Direct the user to the /flows page.\n\n## See also\n\n- [Flow Draft vs Published](/help/flow-draft-vs-published)\n- [How to Deactivate and Reactivate a User](/help/how-to-deactivate-user)\n- [User Roles in Aitomic Flow](/help/user-roles-in-aitomic-flow)',
  'how-to',
  true
),

(
  'Tại sao quy trình không hiển thị hoặc không thể kích hoạt',
  'why-flow-not-visible-vi',
  E'# Tại sao quy trình không hiển thị hoặc không thể kích hoạt\n\nNếu người dùng không thể thấy quy trình trong danh sách hoặc không thể kích hoạt, một trong các lý do sau thường áp dụng.\n\n## Lý do 1: Quy trình đang ở trạng thái Bản nháp\n\nQuy trình phải được **xuất bản** trước khi xuất hiện trong danh sách kích hoạt trên trang /flows. Bản nháp chỉ hiển thị với quản trị viên trong Trình tạo quy trình.\n\n**Cách kiểm tra:** Mở quy trình trong trình tạo. Bảng Xuất bản sẽ hiển thị Bản nháp hoặc số phiên bản đã xuất bản.\n\n**Cách sửa:** Nhấn Xuất bản trong bảng Xuất bản.\n\n## Lý do 2: Hạn chế kích hoạt — phòng ban của người dùng không được phép\n\nQuy trình có thể bị hạn chế với các phòng ban cụ thể. Nếu phòng ban của người dùng không có trong danh sách cho phép, quy trình sẽ không xuất hiện trong danh sách kích hoạt của họ.\n\n**Cách kiểm tra:** Mở trình tạo quy trình → bảng Xuất bản → mục Hạn chế kích hoạt. Nếu có phòng ban được liệt kê, chỉ người dùng trong các phòng ban đó mới thấy quy trình.\n\n**Cách sửa:** Thêm phòng ban của người dùng vào danh sách cho phép, hoặc chuyển người dùng sang phòng ban được phép.\n\n## Lý do 3: Người dùng chưa được gán phòng ban\n\nNếu quy trình có hạn chế kích hoạt và người dùng chưa được gán phòng ban, họ sẽ không khớp với bất kỳ mục nào trong danh sách cho phép.\n\n**Cách sửa:** Gán phòng ban cho người dùng trong trang hồ sơ của họ.\n\n## Lý do 4: Tài khoản người dùng bị vô hiệu hóa\n\nTài khoản không hoạt động không thể xem hoặc kích hoạt bất kỳ quy trình nào.\n\n**Cách kiểm tra:** Mở trang hồ sơ người dùng. Banner **Không hoạt động** màu hổ phách sẽ xuất hiện ở đầu nếu bị vô hiệu hóa.\n\n**Cách sửa:** Nhấn Kích hoạt lại trên trang hồ sơ người dùng.\n\n## Lý do 5: Người dùng đang tìm ở sai nơi\n\nCác quy trình có thể kích hoạt được liệt kê trên trang **/flows** (mục "Quy trình" trong thanh bên trái). Trang /tasks → tab Quy trình của tôi hiển thị các phiên bản người dùng **đã kích hoạt** — không hiển thị quy trình có thể bắt đầu mới.\n\n## Xem thêm\n\n- [Trạng thái Bản nháp và Đã xuất bản](/help/flow-draft-vs-published-vi)\n- [Cách vô hiệu hóa và kích hoạt lại người dùng](/help/how-to-deactivate-user-vi)',
  'how-to',
  true
),

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. How to Export Flow Instance Data to CSV
-- ═══════════════════════════════════════════════════════════════════════════

(
  'How to Export Flow Instance Data to CSV',
  'export-instance-data-csv',
  E'# How to Export Flow Instance Data to CSV\n\nAdmins can export flow instance data to a CSV file for reporting, auditing, or offline analysis in Excel or Google Sheets.\n\n## Where to find the export\n\n1. Go to **Admin → Instances** in the sidebar\n2. Apply any filters you want — the export will include only matching instances\n3. Click the **Export** dropdown button in the top-right area of the page\n4. Choose an export type\n\n## Export types\n\n### Instances export\n\nDownloads one row per flow instance. Columns include:\n\n- Instance ID, flow name, status\n- Triggered by (name + email), triggered-at date\n- Completed / cancelled / error date (if applicable)\n- Step counts: total, pending, completed, skipped\n- One column per form field, across all steps in the matched flows — labelled with the step name and field label\n\nFile-type fields show as "N file(s)" rather than the file contents.\n\n### Attachments export\n\nDownloads one row per uploaded file across all matching instances. Columns include:\n\n- Instance ID, step name, field name\n- Filename and file size\n- A **7-day signed download URL** — paste the URL into a browser or click in Excel to download the file directly\n\nSigned URLs expire 7 days after the export is generated. Re-export to obtain fresh URLs.\n\n## How filters affect the export\n\nThe export honours whatever filters are active in the Instances view at the time you click Export. To export everything, clear all filters first. To export only one flow''s data, set the Flow filter before exporting.\n\n## File format\n\n- UTF-8 encoding with BOM — opens correctly in Excel on Windows and Mac without encoding issues\n- CRLF line endings\n- Standard CSV — import directly into Google Sheets via File → Import\n\n## Who can export\n\nOnly admins can access the Admin → Instances page and the Export function. Regular users cannot export data.\n\n## See also\n\n- [How to View Analytics and Reports](/help/how-to-view-reports)\n- [Understanding the Audit Trail](/help/understanding-audit-trail)',
  'how-to',
  true
),

(
  'Cách xuất dữ liệu phiên bản quy trình sang CSV',
  'export-instance-data-csv-vi',
  E'# Cách xuất dữ liệu phiên bản quy trình sang CSV\n\nQuản trị viên có thể xuất dữ liệu phiên bản quy trình sang tệp CSV để báo cáo, kiểm toán hoặc phân tích ngoại tuyến trong Excel hoặc Google Sheets.\n\n## Tìm tính năng xuất ở đâu\n\n1. Vào **Quản trị → Phiên bản** trong thanh bên\n2. Áp dụng bộ lọc bạn muốn — xuất sẽ chỉ bao gồm các phiên bản khớp\n3. Nhấn nút thả xuống **Xuất** ở góc trên bên phải trang\n4. Chọn loại xuất\n\n## Các loại xuất\n\n### Xuất phiên bản\n\nTải xuống một hàng cho mỗi phiên bản quy trình. Các cột bao gồm:\n\n- ID phiên bản, tên quy trình, trạng thái\n- Người kích hoạt (tên + email), ngày kích hoạt\n- Ngày hoàn thành / hủy / lỗi (nếu có)\n- Số lượng bước: tổng, đang xử lý, đã hoàn thành, đã bỏ qua\n- Một cột cho mỗi trường biểu mẫu trong tất cả các bước, được đặt tên theo tên bước và nhãn trường\n\nCác trường tệp hiển thị là "N tệp" thay vì nội dung tệp.\n\n### Xuất tệp đính kèm\n\nTải xuống một hàng cho mỗi tệp đã tải lên. Các cột bao gồm:\n\n- ID phiên bản, tên bước, tên trường\n- Tên tệp và kích thước tệp\n- **URL tải xuống có chữ ký có hiệu lực 7 ngày** — dán URL vào trình duyệt để tải tệp trực tiếp\n\nURL có chữ ký hết hạn sau 7 ngày kể từ khi xuất. Xuất lại để có URL mới.\n\n## Định dạng tệp\n\n- Mã hóa UTF-8 với BOM — mở đúng trong Excel trên Windows và Mac\n- Phân tách bằng dấu phẩy (CSV) — nhập trực tiếp vào Google Sheets qua Tệp → Nhập\n\n## Ai có thể xuất\n\nChỉ quản trị viên mới có thể truy cập trang Quản trị → Phiên bản và chức năng Xuất.\n\n## Xem thêm\n\n- [Cách xem báo cáo và phân tích](/help/how-to-view-reports-vi)\n- [Tìm hiểu nhật ký kiểm toán](/help/understanding-audit-trail-vi)',
  'how-to',
  true
),

-- ═══════════════════════════════════════════════════════════════════════════
-- 8. How SLA Due Dates Are Calculated (Calendar Hours)
-- ═══════════════════════════════════════════════════════════════════════════

(
  'How SLA Due Dates Are Calculated (Calendar Hours, Not Business Hours)',
  'sla-calendar-hours',
  E'# How SLA Due Dates Are Calculated (Calendar Hours, Not Business Hours)\n\nWhen you set an SLA deadline on a step — for example "Due within 24 hours" — the countdown uses **calendar hours**: continuous 24/7 time that does not pause for evenings, weekends, or public holidays.\n\n## What calendar hours means in practice\n\nA 24-hour SLA that starts at 3:00 PM on Friday expires at 3:00 PM on Saturday, not Monday morning. The clock runs continuously regardless of working days.\n\nThis applies to:\n\n- Step SLA deadlines (the "Due in N hours/days" setting on an Action or Branch node)\n- Escalation timers (the "Escalate after N hours overdue" setting)\n\n## Why calendar hours and not business hours\n\nBusiness-hour calculations require a definition of working days, office hours, and public holidays — which varies by organisation, team, and country. Aitomic Flow uses calendar hours to keep SLA logic simple, consistent, and unambiguous across all tenants.\n\n## How due dates are stored and displayed\n\n- Due dates are stored in **UTC** internally\n- They are displayed in the **viewer''s local timezone** — the same timezone your operating system or browser uses\n- The badge on a pending task shows a colour-coded countdown:\n  - **Red** — the step is overdue (due date has passed)\n  - **Amber** — due within the next 24 hours\n  - **Muted grey** — due in more than 24 hours\n  - **Hidden** — the step has no SLA configured, or it has been completed\n\n## Planning your SLA values\n\nBecause SLA hours run around the clock, factor in overnight and weekend time when deciding what value to use:\n\n| Business-hour target | Suggested calendar-hour SLA |\n|----------------------|-----------------------------|\n| 4 business hours | 24h — covers overnight safely |\n| 1 business day (8h) | 24h |\n| End of next working day | 48h |\n| 2 business days | 48h |\n| 1 week | 120h (5 × 24h) |\n\nAs a practical rule: if the real deadline is N business days, setting the SLA to N × 24 calendar hours is a reasonable conservative approximation for a standard Monday–Friday team.\n\n## Escalation timers use the same logic\n\nThe escalation "after N hours overdue" counter starts the moment the due date passes and also runs in calendar hours. An escalation of 4 hours means the manager receives a notification 4 calendar hours after the deadline, not 4 business hours.\n\n## See also\n\n- [How to Set Deadlines (SLA) on Workflow Steps](/help/how-to-set-sla-deadlines)\n- [Step Escalation: Automatic Manager Notifications](/help/step-escalation-guide)',
  'technical',
  true
),

(
  'Cách tính thời hạn SLA (theo giờ lịch, không phải giờ làm việc)',
  'sla-calendar-hours-vi',
  E'# Cách tính thời hạn SLA (theo giờ lịch, không phải giờ làm việc)\n\nKhi bạn đặt thời hạn SLA cho một bước — ví dụ "Hoàn thành trong 24 giờ" — bộ đếm ngược sử dụng **giờ lịch**: thời gian liên tục 24/7, không dừng vào buổi tối, cuối tuần hay ngày lễ.\n\n## Giờ lịch nghĩa là gì trong thực tế\n\nSLA 24 giờ bắt đầu lúc 3 giờ chiều thứ Sáu sẽ hết hạn lúc 3 giờ chiều thứ Bảy, không phải sáng thứ Hai. Đồng hồ chạy liên tục bất kể ngày làm việc.\n\nĐiều này áp dụng cho:\n\n- Thời hạn SLA của bước (cài đặt "Hoàn thành trong N giờ/ngày" trên nút Action hoặc Branch)\n- Bộ hẹn giờ leo thang (cài đặt "Leo thang sau N giờ quá hạn")\n\n## Tại sao dùng giờ lịch thay vì giờ làm việc\n\nTính toán giờ làm việc yêu cầu định nghĩa về ngày làm việc, giờ văn phòng và ngày lễ — khác nhau theo tổ chức, nhóm và quốc gia. Aitomic Flow sử dụng giờ lịch để giữ cho logic SLA đơn giản và nhất quán.\n\n## Cách lưu trữ và hiển thị thời hạn\n\n- Thời hạn được lưu trữ theo **UTC** nội bộ\n- Hiển thị theo **múi giờ địa phương của người xem**\n- Huy hiệu trên công việc đang xử lý hiển thị bộ đếm ngược màu:\n  - **Đỏ** — bước đã quá hạn\n  - **Vàng hổ phách** — đến hạn trong 24 giờ tới\n  - **Xám mờ** — đến hạn sau hơn 24 giờ\n  - **Ẩn** — bước không có SLA hoặc đã hoàn thành\n\n## Lập kế hoạch giá trị SLA\n\nVì giờ SLA chạy suốt ngày đêm, hãy tính cả thời gian qua đêm và cuối tuần:\n\n| Mục tiêu theo giờ làm việc | Đề xuất SLA theo giờ lịch |\n|---------------------------|---------------------------|\n| 4 giờ làm việc | 24h — bao gồm qua đêm an toàn |\n| 1 ngày làm việc (8h) | 24h |\n| Hết ngày làm việc tiếp theo | 48h |\n| 2 ngày làm việc | 48h |\n| 1 tuần | 120h (5 × 24h) |\n\nQuy tắc thực tế: nếu thời hạn thực là N ngày làm việc, đặt SLA là N × 24 giờ lịch là ước tính bảo thủ hợp lý.\n\n## Bộ hẹn giờ leo thang cũng sử dụng logic tương tự\n\nBộ đếm leo thang "sau N giờ quá hạn" bắt đầu ngay khi thời hạn qua và cũng chạy theo giờ lịch.\n\n## Xem thêm\n\n- [Cách đặt thời hạn (SLA) cho các bước quy trình](/help/how-to-set-sla-deadlines-vi)\n- [Leo thang bước: Thông báo quản lý tự động](/help/step-escalation-guide-vi)',
  'technical',
  true
)

ON CONFLICT (slug) DO NOTHING;
