-- KB: Onboarding drip emails — why admins receive them and what triggers each (EN + VI)

INSERT INTO knowledge_base (title, slug, content_markdown, category, is_active) VALUES

(
  'Why Am I Receiving Onboarding Emails?',
  'onboarding-emails-explained',
  E'# Why Am I Receiving Onboarding Emails?\n\nWhen you create a new Aitomic Flow workspace, the system sends a short series of onboarding emails to the workspace admin. These emails are designed to help you set up your workspace and get your team working as quickly as possible.\n\n## What emails are sent and when?\n\n### Day 1–3: Confirm your email address\n\nIf your email address has not been confirmed yet, you will receive a reminder to check your inbox for the original confirmation link.\n\nTo confirm your email: find the email with the subject **"Please verify your email"** from noreply@aitomicflow.com and click the confirmation link. If you cannot find it, check your spam or junk folder.\n\n### Day 2–5: Your team is waiting\n\nIf you have sent invitations but none of the invited users have accepted yet, you will receive a reminder to follow up. You can resend invitations from the **Invite** page (/invite) under Pending Invitations.\n\nThis email is only sent once and only if there are pending invitations with no accepted members.\n\n### Day 5–9: You are one click away from going live\n\nIf you have published a flow but have not triggered it yet, you will receive a nudge to start your first workflow instance.\n\nGo to the **Flows** page (/flows) and click **Start** next to any published flow to trigger your first run.\n\nThis email is only sent once and only if your workspace has at least one published flow with zero instances ever triggered.\n\n### Day 14–20: Advanced tips\n\nTwo weeks after signup, you will receive one email with tips on three features that workspace admins often discover late:\n\n- **SLA deadlines** — add due dates to workflow steps so assignees are notified automatically when a task is overdue\n- **Department routing** — assign steps to a department instead of a specific person\n- **Flow templates** — clone a ready-made workflow instead of building from scratch\n\nThis email is sent once, unconditionally, to all active workspaces in their second week.\n\n## Can I unsubscribe from these emails?\n\nThese emails are sent to the workspace admin only and are part of the initial onboarding sequence. Each email is sent at most once. Once the sequence is complete (after day 20), no further drip emails are sent.\n\nIf you have questions or want to stop receiving these emails, contact support at contact@aitomicflow.com.\n\n## See also\n\n- [Getting Started Checklist](/help/getting-started-checklist)\n- [How to Invite Users](/help/how-to-invite-users)\n- [How to Start a Workflow](/help/how-to-start-workflow)',
  'account',
  true
),

(
  'Tại sao tôi nhận được email hướng dẫn?',
  'onboarding-emails-explained-vi',
  E'# Tại sao tôi nhận được email hướng dẫn?\n\nKhi bạn tạo không gian làm việc Aitomic Flow mới, hệ thống gửi một loạt email hướng dẫn ngắn đến quản trị viên không gian làm việc. Những email này giúp bạn thiết lập và đưa nhóm vào hoạt động nhanh nhất có thể.\n\n## Những email nào được gửi và khi nào?\n\n### Ngày 1–3: Xác nhận địa chỉ email\n\nNếu địa chỉ email của bạn chưa được xác nhận, bạn sẽ nhận được lời nhắc kiểm tra hộp thư đến để tìm liên kết xác nhận ban đầu.\n\nĐể xác nhận email: tìm email có tiêu đề **"Please verify your email"** từ noreply@aitomicflow.com và nhấp vào liên kết xác nhận. Nếu không tìm thấy, hãy kiểm tra thư mục spam hoặc junk.\n\n### Ngày 2–5: Nhóm của bạn đang chờ\n\nNếu bạn đã gửi lời mời nhưng chưa có ai chấp nhận, bạn sẽ nhận được lời nhắc theo dõi. Bạn có thể gửi lại lời mời từ trang **Mời** (/invite) trong phần Lời mời đang chờ.\n\nEmail này chỉ được gửi một lần và chỉ khi có lời mời đang chờ mà chưa có thành viên nào chấp nhận.\n\n### Ngày 5–9: Bạn chỉ còn một bước nữa\n\nNếu bạn đã xuất bản quy trình nhưng chưa kích hoạt lần nào, bạn sẽ nhận được lời nhắc bắt đầu phiên bản quy trình đầu tiên.\n\nVào trang **Quy trình** (/flows) và nhấn **Bắt đầu** bên cạnh bất kỳ quy trình đã xuất bản nào.\n\nEmail này chỉ được gửi một lần và chỉ khi không gian làm việc của bạn có ít nhất một quy trình đã xuất bản nhưng chưa có phiên bản nào được kích hoạt.\n\n### Ngày 14–20: Mẹo nâng cao\n\nHai tuần sau khi đăng ký, bạn sẽ nhận được một email với mẹo về ba tính năng mà quản trị viên thường khám phá muộn:\n\n- **Hạn chót SLA** — thêm thời hạn cho các bước quy trình để người được giao được thông báo tự động khi quá hạn\n- **Phân công theo phòng ban** — giao bước cho một phòng ban thay vì một người cụ thể\n- **Mẫu quy trình** — sao chép quy trình có sẵn thay vì xây dựng từ đầu\n\nEmail này được gửi một lần, không điều kiện, cho tất cả không gian làm việc đang hoạt động trong tuần thứ hai.\n\n## Tôi có thể hủy đăng ký không?\n\nNhững email này chỉ được gửi đến quản trị viên không gian làm việc và là một phần của chuỗi hướng dẫn ban đầu. Mỗi email được gửi nhiều nhất một lần. Sau khi chuỗi hoàn thành (sau ngày 20), không có email drip nào được gửi thêm.\n\nNếu bạn có câu hỏi hoặc muốn ngừng nhận những email này, hãy liên hệ hỗ trợ tại contact@aitomicflow.com.\n\n## Xem thêm\n\n- [Danh sách kiểm tra bắt đầu](/help/getting-started-checklist-vi)\n- [Cách mời người dùng](/help/how-to-invite-users-vi)\n- [Cách bắt đầu quy trình làm việc](/help/how-to-start-workflow-vi)',
  'account',
  true
)

ON CONFLICT (slug) DO NOTHING;
